/* =====================================================================
 * 星海拾遗 · 银线 v1 · 沉默守夜人
 * 13 主线章 + 4 日常 + 2 隐藏 = 19 节点
 * 设定：玩家=修复师B-13 / 银=前任修复师 M-195（半身义体）
 * 跨线核心：银知道你=林夕，但他选择沉默——告诉你=承认你不是 B-13
 * 银的右眼瞳孔=未来=他已经看见所有可能的结局
 * ====================================================================== */
(function(){
  if (!window.STORY) window.STORY = {};

  window.STORY.yin = [

    /* =========================================================
     *                       Day 1
     * ========================================================= */

    /* ---------- Ch1 第一次值班 ---------- */
    { type:"chapter", day:1, name:"第一章 · 第一次值班", en:"Ch.1 · First Watch", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"凌晨 03:00。星舰穹顶下，只有一道身影站在档案库门口。", term:{ name:"档案库", def:"星舰存放所有被修复者影像与基因样本的核心库。" } },
    { type:"narr", scene:"corridor", text:"他叫银。编号 M-195。心跳停过 7 次。" },
    { type:"narr", scene:"corridor", text:"——他是星舰唯一的守夜人。" },
    { type:"narr", scene:"corridor", fx:"flash", text:"今晚，是你第一次跟班。" },
    { type:"line", who:"yin", exp:"calm", scene:"corridor", text:"……" },
    { type:"line", who:"yin", exp:"calm", text:"修复师 B-13。" },
    { type:"line", who:"player", text:"在。" },
    { type:"line", who:"yin", exp:"calm", text:"档案库守夜，3 条规矩。" },
    { type:"line", who:"yin", exp:"calm", text:"一，不许问名字。" },
    { type:"line", who:"yin", exp:"calm", text:"二，不许碰未编号的胶囊。" },
    { type:"line", who:"yin", exp:"calm", text:"三，3 点 17 分会有人敲门。不许应。" },
    { type:"line", who:"player", text:"……谁？" },
    { type:"line", who:"yin", exp:"calm", text:"不许问。" },
    { type:"countdown", text:"03:17 整。门外传来三声敲击：「咚——咚——咚」。", seconds:7,
      options:[
        { text:"装作没听见，继续抄录档案", success:true, flag:"yin_silence", aff:{yin:2}, next:"q_yin_ch1_silent" },
        { text:"屏息，按规矩不动", success:true, flag:"yin_obey", aff:{yin:1}, next:"q_yin_ch1_obey" },
        { text:"忍不住小声问「谁？」", success:false, flag:"yin_break", aff:{yin:-2}, next:"q_yin_ch1_break" }
      ]
    },
    { type:"label", id:"q_yin_ch1_silent" },
    { type:"line", who:"yin", exp:"calm", text:"……做得好。" },
    { type:"line", who:"yin", exp:"calm", text:"你不像第一次。" },
    { type:"line", who:"player", text:"（——他这句话，为什么像在确认什么？）" },
    { type:"jump", to:"q_yin_ch1_after" },
    { type:"label", id:"q_yin_ch1_obey" },
    { type:"line", who:"yin", exp:"calm", text:"勉强合格。" },
    { type:"jump", to:"q_yin_ch1_after" },
    { type:"label", id:"q_yin_ch1_break" },
    { type:"line", who:"yin", exp:"frown", text:"——B-13。" },
    { type:"line", who:"yin", exp:"frown", text:"我说过，不许应。" },
    { type:"line", who:"yin", exp:"calm", text:"……记住。下次再问，我把你换下。" },
    { type:"label", id:"q_yin_ch1_after" },
    { type:"narr", text:"03:18。门外的脚步声远去。档案库恢复死寂。" },
    { type:"line", who:"yin", exp:"calm", text:"**——这里每一道门外的脚步，都是死人在走。**", important:true },
    { type:"line", who:"yin", exp:"calm", text:"你只要不应，就还是活的。" },

    /* ---------- Ch2 半身 ---------- */
    { type:"chapter", day:1, name:"第二章 · 半身", en:"Ch.2 · Half Body", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"清晨 06:00。交班时间。银在水池边卸下右臂的护甲。" },
    { type:"narr", scene:"corridor", fx:"flash", text:"——一整条银色的金属臂，从肩膀延伸到指尖。" },
    { type:"line", who:"player", text:"……你的手。" },
    { type:"line", who:"yin", exp:"calm", text:"嗯。" },
    { type:"line", who:"yin", exp:"calm", text:"右臂、右肺、右心室、右眼。" },
    { type:"line", who:"yin", exp:"calm", text:"——半个我，是机械的。" },
    { type:"line", who:"player", text:"……为什么？" },
    { type:"line", who:"yin", exp:"calm", text:"12 年前，一次引擎事故。" },
    { type:"line", who:"yin", exp:"calm", text:"我从舱门外把三个人拖了回来。" },
    { type:"line", who:"yin", exp:"calm", text:"代价是我死了。" },
    { type:"line", who:"player", text:"……死了？" },
    { type:"line", who:"yin", exp:"calm", text:"心跳停了 7 分钟。" },
    { type:"line", who:"yin", exp:"calm", text:"他们把我捡回来的时候，只剩半个壳。" },
    { type:"touch", text:"你不自觉地，伸手想碰他的右臂。",
      zones:[
        { id:"arm", label:"右臂金属", success:true, flag:"yin_touch_arm", aff:{yin:1}, text:"指尖触到金属——比想象中温热。", next:"q_yin_ch2_after" },
        { id:"shoulder", label:"右肩接缝", success:true, flag:"yin_touch_seam", aff:{yin:2}, text:"你触到一道极细的接缝。银的呼吸忽然停了一拍。", next:"q_yin_ch2_seam" },
        { id:"hand", label:"右手手心", success:false, flag:"yin_touch_palm", aff:{yin:-1}, text:"你握住他的右手——金属没有温度。他抽回去了。", next:"q_yin_ch2_palm" }
      ]
    },
    { type:"label", id:"q_yin_ch2_seam" },
    { type:"line", who:"yin", exp:"frown", text:"……那里别碰。" },
    { type:"line", who:"yin", exp:"calm", text:"接缝处，还有神经。" },
    { type:"line", who:"player", text:"……对不起。" },
    { type:"line", who:"yin", exp:"calm", text:"嗯。" },
    { type:"jump", to:"q_yin_ch2_after" },
    { type:"label", id:"q_yin_ch2_palm" },
    { type:"line", who:"yin", exp:"calm", text:"机械的手，握不出温度。" },
    { type:"line", who:"yin", exp:"calm", text:"……你不用试。" },
    { type:"label", id:"q_yin_ch2_after" },
    { type:"line", who:"yin", exp:"calm", text:"B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"你不是第一个伸手的人。" },
    { type:"line", who:"yin", exp:"calm", text:"但你是……唯一伸完没问「疼不疼」的人。" },
    { type:"line", who:"player", text:"……应该问吗？" },
    { type:"line", who:"yin", exp:"calm", text:"不该。" },
    { type:"line", who:"yin", exp:"calm", text:"金属不会疼。" },
    { type:"line", who:"yin", exp:"calm", text:"——疼的，是它后面那个人。" },

    /* ---------- Ch3 右眼 ---------- */
    { type:"chapter", day:1, name:"第三章 · 右眼", en:"Ch.3 · Right Eye", scene:"deck" },
    { type:"narr", scene:"deck", text:"中午。观星甲板。银背对着你站着，看星图。" },
    { type:"narr", scene:"deck", text:"他左眼是普通的灰，右眼里却映着一整片旋转的银河。" },
    { type:"line", who:"player", text:"……你的右眼。" },
    { type:"line", who:"yin", exp:"calm", text:"嗯。" },
    { type:"line", who:"yin", exp:"calm", text:"植入式星图。" },
    { type:"line", who:"yin", exp:"calm", text:"左眼，是过去。" },
    { type:"line", who:"yin", exp:"calm", text:"右眼，是未来。" },
    { type:"line", who:"player", text:"……你能看见未来？" },
    { type:"line", who:"yin", exp:"calm", text:"看见所有可能的未来。" },
    { type:"line", who:"yin", exp:"calm", text:"——也包括，所有可能的结局。" },
    { type:"line", who:"player", text:"那……你看见我的结局了吗？" },
    { type:"line", who:"yin", exp:"calm", text:"……看见了。" },
    { type:"line", who:"yin", exp:"sad", text:"很多个。" },
    { type:"swipe", text:"他闭上右眼，又睁开。你听见一段非常轻的喘息。",
      direction:"down",
      success:{ text:"你伸手轻轻按住他的右眼皮——「别看了。」", flag:"yin_eye_cover", aff:{yin:3}, next:"q_yin_ch3_cover" },
      fail:{ text:"你愣在原地，没有动。", flag:"yin_eye_freeze", aff:{yin:0}, next:"q_yin_ch3_freeze" }
    },
    { type:"label", id:"q_yin_ch3_cover" },
    { type:"line", who:"yin", exp:"sad", text:"……" },
    { type:"line", who:"yin", exp:"calm", text:"你是第二个，让我闭上右眼的人。" },
    { type:"line", who:"player", text:"……第一个是谁？" },
    { type:"line", who:"yin", exp:"calm", text:"——一个 14 岁的孩子。" },
    { type:"line", who:"yin", exp:"calm", text:"那孩子说：「**别看了。我替你看。**」", important:true },
    { type:"line", who:"player", text:"……" },
    { type:"line", who:"player", text:"（——为什么这句话，听起来这么熟？）" },
    { type:"jump", to:"q_yin_ch3_after" },
    { type:"label", id:"q_yin_ch3_freeze" },
    { type:"line", who:"yin", exp:"calm", text:"没事。" },
    { type:"line", who:"yin", exp:"calm", text:"你不用替我做什么。" },
    { type:"line", who:"yin", exp:"calm", text:"……毕竟我们才认识不到一天。" },
    { type:"label", id:"q_yin_ch3_after" },
    { type:"line", who:"yin", exp:"calm", text:"B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"你今晚还守夜吗？" },
    { type:"line", who:"player", text:"——守。" },
    { type:"line", who:"yin", exp:"calm", text:"那……记住第 3 条。" },
    { type:"line", who:"yin", exp:"calm", text:"——3 点 17 分，不许应。" },

    /* ---------- Ch4 第二夜 ---------- */
    { type:"chapter", day:1, name:"第四章 · 第二夜", en:"Ch.4 · Second Night", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"凌晨 03:00。第二次值班。" },
    { type:"narr", scene:"corridor", text:"档案库灯光发蓝。银坐在你对面，低头擦一把短匕首。" },
    { type:"line", who:"yin", exp:"calm", text:"B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"今晚特殊。" },
    { type:"line", who:"yin", exp:"calm", text:"03:17，可能会有第二种声音。" },
    { type:"line", who:"player", text:"……什么声音？" },
    { type:"line", who:"yin", exp:"calm", text:"——你的名字。" },
    { type:"line", who:"yin", exp:"calm", text:"门外，有人会叫你的名字。" },
    { type:"line", who:"yin", exp:"calm", text:"无论你听见什么，都不许应。" },
    { type:"narr", text:"03:17：00。门外是绝对的死寂。" },
    { type:"narr", text:"03:17：04。一声极轻的叹息。" },
    { type:"narr", fx:"flash", text:"03:17：09。一个非常温柔的男声响起——" },
    { type:"line", who:"narrator", text:"——林夕，回家了。" },
    { type:"countdown", text:"那个名字像一根针扎进你脑子。你的手指开始颤抖。你必须做选择。", seconds:10,
      options:[
        { text:"咬住舌头，一声不应", success:true, flag:"yin_n2_silent", aff:{yin:3}, next:"q_yin_ch4_silent" },
        { text:"抬头去看银——求救", success:true, flag:"yin_n2_lookyin", aff:{yin:2}, next:"q_yin_ch4_look" },
        { text:"忍不住，低声「……谁？」", success:false, flag:"yin_n2_ask", aff:{yin:-3}, next:"q_yin_ch4_ask" }
      ]
    },
    { type:"label", id:"q_yin_ch4_silent" },
    { type:"narr", text:"——03:18。脚步远去。" },
    { type:"line", who:"yin", exp:"calm", text:"……做得好。" },
    { type:"line", who:"yin", exp:"calm", text:"非常好。" },
    { type:"line", who:"player", text:"……那个声音叫的「林夕」是谁？" },
    { type:"line", who:"yin", exp:"calm", text:"……" },
    { type:"line", who:"yin", exp:"calm", text:"——我不能告诉你。" },
    { type:"jump", to:"q_yin_ch4_after" },
    { type:"label", id:"q_yin_ch4_look" },
    { type:"line", who:"yin", exp:"calm", text:"看我。" },
    { type:"line", who:"yin", exp:"calm", text:"——眼睛看我。" },
    { type:"narr", text:"你死死盯着银的左眼。03:18。脚步远去。" },
    { type:"line", who:"yin", exp:"calm", text:"……可以了。" },
    { type:"jump", to:"q_yin_ch4_after" },
    { type:"label", id:"q_yin_ch4_ask" },
    { type:"line", who:"yin", exp:"frown", text:"——B-13。" },
    { type:"narr", fx:"flash", text:"档案库的灯，全部熄灭。" },
    { type:"line", who:"yin", exp:"frown", text:"快躲到我背后。" },
    { type:"narr", text:"你听见门外的脚步声，朝档案库里走了进来。" },
    { type:"line", who:"yin", exp:"frown", text:"——闭眼。" },
    { type:"line", who:"yin", exp:"calm", text:"……不许睁开。" },
    { type:"end", tag:"BE", title:"应声·失格",
      en:"Answered · Disqualified",
      body:"你应了不该应的人。\n第二天，你的编号 B-13，从星舰名单上消失。\n银独自一人，留在档案库守夜。\n他左眼里那个 14 岁的孩子，又少了一个。\n\n——请回到第四章重选。" },
    { type:"label", id:"q_yin_ch4_after" },
    { type:"line", who:"yin", exp:"calm", text:"B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"今晚你救了你自己。" },
    { type:"line", who:"player", text:"……我没做什么。" },
    { type:"line", who:"yin", exp:"calm", text:"不做，就是救。" },

    /* ---------- 日常 1 凌晨四点的粥 ---------- */
    { type:"chapter", day:1, name:"日常 · 凌晨四点的粥", en:"Daily · 04AM Porridge", scene:"cabin" },
    { type:"narr", scene:"cabin", text:"凌晨 04:00。守夜结束。星舰餐厅只剩你和银。" },
    { type:"narr", scene:"cabin", text:"他从机械臂的指节里弹出一个小小的恒温罐——里面是一碗热粥。" },
    { type:"line", who:"yin", exp:"calm", text:"——给。" },
    { type:"line", who:"player", text:"……你的手里，还能装这个？" },
    { type:"line", who:"yin", exp:"calm", text:"自己改的。" },
    { type:"line", who:"yin", exp:"calm", text:"守夜的人，需要一碗热的。" },
    { type:"line", who:"player", text:"……谢谢。" },
    { type:"line", who:"yin", exp:"calm", text:"嗯。" },
    { type:"narr", text:"粥是白米粥，配了一小撮咸菜。你吃得很慢。" },
    { type:"line", who:"yin", exp:"calm", text:"……" },
    { type:"line", who:"yin", exp:"calm", text:"你吃饭的样子。" },
    { type:"line", who:"yin", exp:"calm", text:"和那个孩子，一模一样。" },
    { type:"line", who:"player", text:"——哪个孩子？" },
    { type:"line", who:"yin", exp:"calm", text:"……不重要了。" },

    /* =========================================================
     *                       Day 2
     * ========================================================= */

    /* ---------- Ch5 旧档案 ---------- */
    { type:"chapter", day:2, name:"第五章 · 旧档案", en:"Ch.5 · Old Files", scene:"archive" },
    { type:"narr", scene:"archive", text:"第二天上午。银破例让你进了 B 区——12 年前事故那一批档案的存放区。", term:{ name:"B 区", def:"星舰档案库内编号 B 字头的私人区，只有守夜人持有权限。" } },
    { type:"line", who:"yin", exp:"calm", text:"——你说要查 12 年前。" },
    { type:"line", who:"yin", exp:"calm", text:"那批人的胶囊编号，从 M-191 到 M-200。" },
    { type:"line", who:"yin", exp:"calm", text:"——一共 10 个。" },
    { type:"line", who:"player", text:"……你是 M-195。" },
    { type:"line", who:"yin", exp:"calm", text:"嗯。" },
    { type:"line", who:"player", text:"——M-194？" },
    { type:"line", who:"yin", exp:"calm", text:"……一位工程师。已故。" },
    { type:"line", who:"player", text:"——M-193？" },
    { type:"line", who:"yin", exp:"calm", text:"——千夜博士。" },
    { type:"line", who:"player", text:"——M-192？" },
    { type:"line", who:"yin", exp:"calm", text:"——云璃。" },
    { type:"line", who:"player", text:"……" },
    { type:"line", who:"player", text:"——M-200？" },
    { type:"drag", text:"银沉默了。他用机械臂把一份档案推过来，让你自己打开。",
      from:"档案", to:"打开",
      success:{ text:"档案标题：「M-200 · 林夕 · 14 岁 · 工程师学徒 · 殉职」", flag:"yin_lin_xi_dead", aff:{yin:1}, next:"q_yin_ch5_after" },
      fail:{ text:"档案太重，你的手滑了一下，没打开。", flag:"yin_lin_xi_slip", aff:{yin:0}, next:"q_yin_ch5_skip" }
    },
    { type:"label", id:"q_yin_ch5_skip" },
    { type:"line", who:"yin", exp:"calm", text:"——下次再看。" },
    { type:"label", id:"q_yin_ch5_after" },
    { type:"line", who:"player", text:"……林夕。" },
    { type:"line", who:"player", text:"为什么这个名字，我听过？" },
    { type:"line", who:"yin", exp:"calm", text:"……" },
    { type:"line", who:"yin", exp:"calm", text:"B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"档案到此为止。" },
    { type:"line", who:"yin", exp:"calm", text:"**——不许再查。**", important:true },

    /* ---------- Ch6 14 岁的孩子 ---------- */
    { type:"chapter", day:2, name:"第六章 · 14 岁的孩子", en:"Ch.6 · The 14yo", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"傍晚。星舰走廊。你独自一人沿着 B 区走，墙上贴着 12 年前那批殉职者的照片。" },
    { type:"narr", scene:"corridor", text:"在「M-200 林夕」的那张照片前，你停下了。" },
    { type:"narr", scene:"corridor", fx:"flash", text:"照片里，一个 14 岁的男孩抱着工具箱，站在 M-194 工程师身边笑。" },
    { type:"narr", scene:"corridor", text:"——那张脸。和你镜子里，几乎一样。" },
    { type:"line", who:"player", text:"……" },
    { type:"line", who:"yin", exp:"calm", scene:"corridor", text:"B-13。" },
    { type:"line", who:"player", text:"——银。这个孩子是谁？" },
    { type:"line", who:"yin", exp:"calm", text:"……" },
    { type:"line", who:"yin", exp:"calm", text:"——一个殉职的学徒。" },
    { type:"line", who:"yin", exp:"calm", text:"12 年前，引擎事故。" },
    { type:"line", who:"yin", exp:"calm", text:"他冲进引擎舱，按下了关闭按钮——救了所有人。" },
    { type:"line", who:"player", text:"……包括你？" },
    { type:"line", who:"yin", exp:"sad", text:"——包括我。" },
    { type:"voice", text:"你忽然非常想叫他一个字。",
      target:["哥","哥哥","师兄"],
      success:{ text:"你脱口而出——「哥。」", flag:"yin_call_brother", aff:{yin:5}, next:"q_yin_ch6_bro" },
      fail:{ text:"你张嘴，又把那个字咽了回去。", flag:"yin_no_bro", aff:{yin:0}, next:"q_yin_ch6_no" }
    },
    { type:"label", id:"q_yin_ch6_bro" },
    { type:"line", who:"yin", exp:"shock", text:"——B-13。" },
    { type:"line", who:"yin", exp:"sad", text:"……这个字。" },
    { type:"line", who:"yin", exp:"sad", text:"你不要随便叫。" },
    { type:"line", who:"player", text:"……为什么？" },
    { type:"line", who:"yin", exp:"calm", text:"因为——叫得我心跳又开始疼。" },
    { type:"jump", to:"q_yin_ch6_after" },
    { type:"label", id:"q_yin_ch6_no" },
    { type:"line", who:"yin", exp:"calm", text:"……不要叫。" },
    { type:"line", who:"yin", exp:"calm", text:"——别问我为什么。" },
    { type:"label", id:"q_yin_ch6_after" },
    { type:"line", who:"yin", exp:"calm", text:"B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"你不是林夕。" },
    { type:"line", who:"yin", exp:"calm", text:"——林夕，已经死了。" },
    { type:"line", who:"yin", exp:"sad", text:"……死在我怀里。" },

    /* ---------- Ch7 心跳停过 7 次 ---------- */
    { type:"chapter", day:2, name:"第七章 · 心跳停过 7 次", en:"Ch.7 · Seven Stops", scene:"medbay" },
    { type:"narr", scene:"medbay", text:"夜里 22:00。医疗舱。" },
    { type:"narr", scene:"medbay", text:"银躺在维护台上，机械胸腔打开——里面是一颗半生物半机械的心。", term:{ name:"半生物心", def:"将原生心室与机械泵融合的义体——每年必须维护一次。" } },
    { type:"line", who:"yin", exp:"calm", text:"B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"今年第 7 次维护。" },
    { type:"line", who:"yin", exp:"calm", text:"——也是最后一次。" },
    { type:"line", who:"player", text:"……最后一次？" },
    { type:"line", who:"yin", exp:"calm", text:"这颗心，再撑不过半年。" },
    { type:"line", who:"yin", exp:"calm", text:"上一次心跳停止，已经停了 17 分钟。" },
    { type:"line", who:"yin", exp:"calm", text:"——医生说，下一次启不动，就让它停。" },
    { type:"line", who:"player", text:"——为什么不换一颗全机械的？" },
    { type:"line", who:"yin", exp:"calm", text:"……" },
    { type:"line", who:"yin", exp:"sad", text:"全机械的，记不住人。" },
    { type:"line", who:"yin", exp:"calm", text:"——我留着这半颗，是想记住一个人。" },
    { type:"qte", text:"——监护仪忽然报警。银的心跳，正在停止。", seconds:6,
      success:{ text:"你按住他的胸口，喊医师，按压、注射、电击——心跳，回来了。", flag:"yin_save_heart", aff:{yin:5}, next:"q_yin_ch7_save" },
      fail:{ text:"你愣了 6 秒。银的心跳，第 8 次停止。", flag:"yin_lose_heart", aff:{yin:-5}, next:"q_yin_ch7_lose" }
    },
    { type:"label", id:"q_yin_ch7_save" },
    { type:"line", who:"yin", exp:"calm", text:"……回来了。" },
    { type:"line", who:"yin", exp:"calm", text:"B-13。" },
    { type:"line", who:"yin", exp:"sad", text:"——你是第二个，把我从死里拽回来的人。" },
    { type:"line", who:"player", text:"……第一个，是林夕？" },
    { type:"line", who:"yin", exp:"sad", text:"……嗯。" },
    { type:"line", who:"yin", exp:"sad", text:"12 年前，他用尽最后力气，按住了我的胸口。" },
    { type:"line", who:"yin", exp:"sad", text:"他说——「**哥，别死。我替你死。**」", important:true },
    { type:"jump", to:"q_yin_ch7_after" },
    { type:"label", id:"q_yin_ch7_lose" },
    { type:"narr", text:"监护仪拉成一条直线。银的右眼，慢慢熄灭。" },
    { type:"end", tag:"BE", title:"第八次停止",
      en:"Eighth Stop",
      body:"心跳停了。\n你看着那颗半生物半机械的心，最后一次安静下来。\n银的右眼，星图熄灭。\n他没说一句遗言。\n——但你知道，他本来想叫你「林夕」。\n\n——请回到第七章，按时按下电击。" },
    { type:"label", id:"q_yin_ch7_after" },
    { type:"line", who:"player", text:"……" },
    { type:"line", who:"player", text:"——为什么，他要替你死？" },
    { type:"line", who:"yin", exp:"sad", text:"因为我对他说过——「你长大了，要替我看完未来。」" },
    { type:"line", who:"yin", exp:"sad", text:"……他记住了。" },

    /* ---------- Ch8 你不是林夕 ---------- */
    { type:"chapter", day:2, name:"第八章 · 你不是林夕", en:"Ch.8 · You Are Not Linxi", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"深夜 23:30。银从医疗舱出来。你跟在他身后，一路没说话。" },
    { type:"line", who:"player", text:"——银。" },
    { type:"line", who:"yin", exp:"calm", text:"嗯。" },
    { type:"line", who:"player", text:"——我是林夕，对不对？" },
    { type:"line", who:"yin", exp:"calm", text:"……" },
    { type:"line", who:"yin", exp:"calm", text:"——你不是。" },
    { type:"line", who:"player", text:"那为什么这张照片，和我一样？" },
    { type:"line", who:"player", text:"为什么那一声「林夕」，我会差点应？" },
    { type:"line", who:"player", text:"为什么我叫你「哥」，你心跳又开始疼？" },
    { type:"line", who:"yin", exp:"sad", text:"……" },
    { type:"line", who:"yin", exp:"sad", text:"B-13。" },
    { type:"line", who:"yin", exp:"sad", text:"——你不是林夕。" },
    { type:"line", who:"yin", exp:"sad", text:"你是用林夕的基因，造出来的「修复师 B-13」。" },
    { type:"line", who:"yin", exp:"sad", text:"——你是星舰用他剩下的细胞，培养了 12 年的复制人。" },
    { type:"line", who:"player", text:"……" },
    { type:"swipe", text:"——你的大脑一片空白。手指在颤抖。",
      direction:"any",
      success:{ text:"你深吸一口气，没有崩溃。", flag:"yin_truth_stand", aff:{yin:3}, next:"q_yin_ch8_stand" },
      fail:{ text:"你扶住墙，眼前一黑。", flag:"yin_truth_fall", aff:{yin:0}, next:"q_yin_ch8_fall" }
    },
    { type:"label", id:"q_yin_ch8_stand" },
    { type:"line", who:"player", text:"……那我究竟，算是林夕，还是 B-13？" },
    { type:"line", who:"yin", exp:"sad", text:"——你想是谁，就是谁。" },
    { type:"line", who:"yin", exp:"calm", text:"林夕在我心里，永远 14 岁。" },
    { type:"line", who:"yin", exp:"calm", text:"——B-13 在我面前，已经 26 岁。" },
    { type:"line", who:"yin", exp:"calm", text:"……你不必，做他的影子。" },
    { type:"jump", to:"q_yin_ch8_after" },
    { type:"label", id:"q_yin_ch8_fall" },
    { type:"line", who:"yin", exp:"sad", text:"……扶住我。" },
    { type:"line", who:"yin", exp:"calm", text:"——慢慢呼吸。" },
    { type:"line", who:"yin", exp:"calm", text:"你不必现在选。" },
    { type:"label", id:"q_yin_ch8_after" },
    { type:"line", who:"yin", exp:"calm", text:"**——林夕已经死了。你是你。**", important:true },
    { type:"line", who:"yin", exp:"calm", text:"——但今晚，让我抱你一下。" },
    { type:"line", who:"yin", exp:"calm", text:"……就一下。" },
    { type:"line", who:"player", text:"……嗯。" },

    /* ---------- 日常 2 守夜人协议 ---------- */
    { type:"chapter", day:2, name:"日常 · 守夜人协议", en:"Daily · Night Pact", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"次日凌晨 02:30。守夜前 30 分钟。" },
    { type:"narr", scene:"corridor", text:"银递给你一把短匕首——和他自己那把一样。" },
    { type:"line", who:"yin", exp:"calm", text:"——给你。" },
    { type:"line", who:"yin", exp:"calm", text:"以后你也算半个守夜人。" },
    { type:"line", who:"player", text:"……这把匕首，是做什么用的？" },
    { type:"line", who:"yin", exp:"calm", text:"——03:17，如果有人破门而入。" },
    { type:"line", who:"yin", exp:"calm", text:"先割断自己的护甲带子。" },
    { type:"line", who:"yin", exp:"calm", text:"——再保护对方。" },
    { type:"line", who:"player", text:"……为什么先割自己？" },
    { type:"line", who:"yin", exp:"calm", text:"因为守夜人，先死。" },
    { type:"line", who:"yin", exp:"calm", text:"——这是规矩。" },

    /* ---------- 日常 3 第二只机械臂 ---------- */
    { type:"chapter", day:2, name:"日常 · 第二只机械臂", en:"Daily · Second Arm", scene:"workshop" },
    { type:"narr", scene:"workshop", text:"下午。工坊。云璃悄悄塞给你一只小机械护腕——里面藏了一颗微型急救器。" },
    { type:"line", who:"yunli", exp:"smile", scene:"workshop", text:"——林夕……啊不，B-13，给你。" },
    { type:"line", who:"yunli", exp:"calm", text:"我父亲临终前，给银做过一只这种的。" },
    { type:"line", who:"yunli", exp:"calm", text:"现在我做了第二只，送你。" },
    { type:"line", who:"player", text:"……为什么送我？" },
    { type:"line", who:"yunli", exp:"smile", text:"因为——你是唯一让他闭过右眼的人。" },
    { type:"line", who:"yunli", exp:"smile", text:"求你，让他多活几年。" },

    /* ---------- 隐藏 1 林夕的录音 ---------- */
    { type:"chapter", day:2, name:"隐藏 · 14 岁的录音", en:"Hidden · 14yo Tape", scene:"archive" },
    { type:"narr", scene:"archive", text:"档案库最底层。一个无编号的木盒。里面是一卷老式磁带。" },
    { type:"narr", scene:"archive", text:"标签上手写：「哥——林夕」。" },
    { type:"line", who:"narrator", text:"——哥，如果哪天我先死了。" },
    { type:"line", who:"narrator", text:"——你不许跟着死。" },
    { type:"line", who:"narrator", text:"——你的眼睛能看见未来。你要替我看完。" },
    { type:"line", who:"narrator", text:"——看完所有结局，再来找我。" },
    { type:"line", who:"narrator", text:"——哥，听见了吗？" },
    { type:"player_silhouette", text:"（——你的剪影站在播放器前。眼泪从下巴滴下来。）" },
    { type:"player_reveal" },
    { type:"line", who:"player", text:"……哥。" },
    { type:"line", who:"player", text:"——我替他，替你看完了。" },

    /* =========================================================
     *                       Day 3
     * ========================================================= */

    /* ---------- Ch9 第三夜 · 来访者 ---------- */
    { type:"chapter", day:3, name:"第九章 · 第三夜·来访者", en:"Ch.9 · The Visitor", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"第三天凌晨 03:00。你和银，第三次值班。" },
    { type:"narr", scene:"corridor", fx:"flash", text:"今晚不一样——警报响了。" },
    { type:"line", who:"yin", exp:"frown", text:"——B-13，戒备。" },
    { type:"line", who:"yin", exp:"frown", text:"今晚 03:17，会真的有人进来。" },
    { type:"line", who:"player", text:"——谁？" },
    { type:"line", who:"yin", exp:"calm", text:"——12 年前那场事故的「另一个幸存者」。" },
    { type:"line", who:"yin", exp:"calm", text:"——他来取一样东西。" },
    { type:"line", who:"player", text:"——什么东西？" },
    { type:"line", who:"yin", exp:"calm", text:"……你。" },
    { type:"line", who:"yin", exp:"calm", text:"——他来取「林夕的复制人」。" },
    { type:"countdown", text:"03:17 整。档案库的门，从外面被一只机械手推开。", seconds:8,
      options:[
        { text:"按守夜人协议——割断护甲带，挡在银身前", success:true, flag:"yin_protect_yin", aff:{yin:5}, next:"q_yin_ch9_protect" },
        { text:"躲在银身后", success:false, flag:"yin_hide", aff:{yin:-2}, next:"q_yin_ch9_hide" },
        { text:"拔匕首，独自冲过去", success:false, flag:"yin_charge", aff:{yin:-3}, next:"q_yin_ch9_charge" }
      ]
    },
    { type:"label", id:"q_yin_ch9_protect" },
    { type:"line", who:"yin", exp:"shock", text:"——B-13，退后。" },
    { type:"line", who:"player", text:"——不退。守夜人协议，第一条。" },
    { type:"line", who:"yin", exp:"sad", text:"……" },
    { type:"line", who:"yin", exp:"sad", text:"——你这小子。" },
    { type:"jump", to:"q_yin_ch9_after" },
    { type:"label", id:"q_yin_ch9_hide" },
    { type:"line", who:"yin", exp:"calm", text:"——好。" },
    { type:"line", who:"yin", exp:"calm", text:"我来挡。" },
    { type:"jump", to:"q_yin_ch9_after" },
    { type:"label", id:"q_yin_ch9_charge" },
    { type:"line", who:"yin", exp:"frown", text:"——回来！" },
    { type:"narr", text:"你冲过去的瞬间，对方的机械手抓住了你的喉咙。" },
    { type:"end", tag:"BE", title:"莽撞·失踪",
      en:"Reckless · Vanished",
      body:"对方把你带走了。\n第二天，星舰上不再有 B-13。\n银独自一人，在档案库里坐了 3 天，没说一句话。\n他的右眼，从此再不睁开。\n\n——请回到第九章，选「守夜人协议」。" },
    { type:"label", id:"q_yin_ch9_after" },
    { type:"narr", text:"对方走出阴影——是一个全机械义体的男人。" },
    { type:"line", who:"narrator", text:"——M-195。把林夕的复制人交出来。" },
    { type:"line", who:"yin", exp:"frown", text:"——M-191。你不该来。" },
    { type:"line", who:"narrator", text:"——12 年前你欠我一条命。" },
    { type:"line", who:"narrator", text:"——现在我来收。" },

    /* ---------- Ch10 M-191 ---------- */
    { type:"chapter", day:3, name:"第十章 · M-191", en:"Ch.10 · M-191", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"M-191 是 12 年前事故的总指挥。" },
    { type:"narr", scene:"corridor", text:"事故后，他被改造成 100% 机械义体——他没有半颗生物心。" },
    { type:"narr", scene:"corridor", text:"——他要带走「林夕的复制人」，做星舰新的舰长备份。" },
    { type:"line", who:"narrator", text:"——M-195。让开。" },
    { type:"line", who:"yin", exp:"calm", text:"——不让。" },
    { type:"line", who:"narrator", text:"——他不是林夕。他只是个备份。" },
    { type:"line", who:"yin", exp:"calm", text:"……" },
    { type:"line", who:"yin", exp:"calm", text:"——他是 B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"——是一个独立的人。" },
    { type:"line", who:"yin", exp:"calm", text:"**——他不是任何人的备份。**", important:true },
    { type:"line", who:"narrator", text:"——你这颗半生物心，还能撑几下？" },
    { type:"line", who:"yin", exp:"calm", text:"——撑一下，就够了。" },
    { type:"qte", text:"——M-191 的机械手刺向银的胸口。你必须替他挡。", seconds:5,
      success:{ text:"你扑过去，匕首贴住对方机械腕——硬生生卸下了他半只手。", flag:"yin_block_m191", aff:{yin:5}, next:"q_yin_ch10_block" },
      fail:{ text:"你慢了一拍。机械手刺穿了银的胸腔。", flag:"yin_late", aff:{yin:-5}, next:"q_yin_ch10_late" }
    },
    { type:"label", id:"q_yin_ch10_block" },
    { type:"line", who:"yin", exp:"shock", text:"——B-13……" },
    { type:"line", who:"yin", exp:"calm", text:"……谢谢。" },
    { type:"jump", to:"q_yin_ch10_after" },
    { type:"label", id:"q_yin_ch10_late" },
    { type:"narr", text:"银的半生物心，第 8 次停止。这一次，没人能再启动它。" },
    { type:"end", tag:"BE", title:"慢一拍",
      en:"One Beat Late",
      body:"你慢了一拍。\n银的半颗心，停在了你怀里。\n他最后一句话是——「替我看完……未来。」\n他的右眼，星图熄灭。\n\n——请回到第十章，按时按下 QTE。" },
    { type:"label", id:"q_yin_ch10_after" },
    { type:"narr", text:"M-191 倒下。他的中央处理器被卸下——失去战斗能力。" },
    { type:"line", who:"yin", exp:"calm", text:"……你做到了。" },

    /* ---------- Ch11 真名 ---------- */
    { type:"chapter", day:3, name:"第十一章 · 真名", en:"Ch.11 · True Name", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"凌晨 04:00。档案库恢复死寂。" },
    { type:"narr", scene:"corridor", text:"银坐在地上，机械胸腔发出沉闷的回响。" },
    { type:"line", who:"yin", exp:"calm", text:"——B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"——把你的真名，告诉我。" },
    { type:"line", who:"player", text:"……我没有真名。" },
    { type:"line", who:"yin", exp:"calm", text:"——你有。" },
    { type:"line", who:"yin", exp:"calm", text:"——你自己取一个。" },
    { type:"line", who:"yin", exp:"calm", text:"——不许叫林夕。" },
    { type:"voice", text:"你深吸一口气，对着银，叫了一个名字。",
      target:["夜","夜守","守夜","知夜","知秋","B-13"],
      success:{ text:"你叫了——「**知夜。**」", flag:"yin_name_zhiye", aff:{yin:5}, next:"q_yin_ch11_name" },
      fail:{ text:"你叫不出来。最后还是叫了——「B-13。」", flag:"yin_name_b13", aff:{yin:1}, next:"q_yin_ch11_b13" }
    },
    { type:"label", id:"q_yin_ch11_name" },
    { type:"line", who:"yin", exp:"shock", text:"——知夜？" },
    { type:"line", who:"yin", exp:"calm", text:"——知道我守夜。" },
    { type:"line", who:"yin", exp:"sad", text:"……好。" },
    { type:"line", who:"yin", exp:"sad", text:"——知夜，是个好名字。" },
    { type:"line", who:"yin", exp:"sad", text:"**——知夜，林夕已经走了。从今晚起，是你和我守夜。**", important:true },
    { type:"jump", to:"q_yin_ch11_after" },
    { type:"label", id:"q_yin_ch11_b13" },
    { type:"line", who:"yin", exp:"calm", text:"……B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"——也行。" },
    { type:"line", who:"yin", exp:"calm", text:"——那我以后，叫你 13。" },
    { type:"label", id:"q_yin_ch11_after" },
    { type:"line", who:"yin", exp:"calm", text:"——从今晚起，守夜人协议第一条改了。" },
    { type:"line", who:"yin", exp:"calm", text:"——守夜人，不许先死。" },
    { type:"line", who:"yin", exp:"calm", text:"——两个人，一起活。" },

    /* ---------- Ch12 右眼的最后一帧 ---------- */
    { type:"chapter", day:3, name:"第十二章 · 右眼的最后一帧", en:"Ch.12 · The Last Frame", scene:"deck" },
    { type:"narr", scene:"deck", text:"清晨 06:00。观星甲板。星舰穿过一片紫色的星云。" },
    { type:"narr", scene:"deck", text:"银背对着你站着，右眼缓缓关闭。" },
    { type:"line", who:"yin", exp:"calm", text:"——B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"——我的右眼，今天看完了最后一帧未来。" },
    { type:"line", who:"player", text:"——是什么？" },
    { type:"line", who:"yin", exp:"smile", text:"——你站在我旁边。" },
    { type:"line", who:"yin", exp:"smile", text:"——头发是白的。" },
    { type:"line", who:"yin", exp:"smile", text:"——还在叫我「哥」。" },
    { type:"line", who:"player", text:"……" },
    { type:"line", who:"player", text:"——那是多少年后？" },
    { type:"line", who:"yin", exp:"smile", text:"——很多很多年。" },
    { type:"line", who:"yin", exp:"smile", text:"——所以这半颗心，必须撑过去。" },
    { type:"touch", text:"你想替他做点什么。",
      zones:[
        { id:"chest", label:"半生物胸口", success:true, flag:"yin_touch_chest", aff:{yin:5}, text:"你轻轻按住他的胸口——心跳，稳定。", next:"q_yin_ch12_chest" },
        { id:"eye", label:"已闭上的右眼", success:true, flag:"yin_touch_eye2", aff:{yin:3}, text:"你的指尖盖住他的右眼皮——「以后我替你看。」", next:"q_yin_ch12_eye" },
        { id:"hand", label:"机械右手", success:true, flag:"yin_take_hand", aff:{yin:2}, text:"你握住他的机械右手。这次他没抽回。", next:"q_yin_ch12_hand" }
      ]
    },
    { type:"label", id:"q_yin_ch12_chest" },
    { type:"line", who:"yin", exp:"sad", text:"……你的手很暖。" },
    { type:"line", who:"yin", exp:"sad", text:"暖到，我这颗半生物心，又愿意多撑几下了。" },
    { type:"jump", to:"q_yin_ch12_after" },
    { type:"label", id:"q_yin_ch12_eye" },
    { type:"line", who:"yin", exp:"sad", text:"……好。" },
    { type:"line", who:"yin", exp:"sad", text:"——以后未来，归你看。" },
    { type:"jump", to:"q_yin_ch12_after" },
    { type:"label", id:"q_yin_ch12_hand" },
    { type:"line", who:"yin", exp:"sad", text:"……机械的手，握不出温度。" },
    { type:"line", who:"yin", exp:"sad", text:"——但你的温度，传过来了。" },
    { type:"label", id:"q_yin_ch12_after" },
    { type:"line", who:"yin", exp:"calm", text:"——B-13。" },
    { type:"line", who:"yin", exp:"calm", text:"——以后值夜，不许迟到。" },
    { type:"line", who:"player", text:"——不迟到。" },
    { type:"line", who:"player", text:"——一辈子。" },

    /* ---------- 隐藏 2 林夕给你的信 ---------- */
    { type:"chapter", day:3, name:"隐藏 · 林夕给你的信", en:"Hidden · Letter to You", scene:"archive" },
    { type:"narr", scene:"archive", text:"档案库 B 区最深处。一封用 12 年前的纸写的信。收信人：「未来的我」。" },
    { type:"line", who:"narrator", text:"——你好。" },
    { type:"line", who:"narrator", text:"——如果你正在读这封信，说明我已经成功了。" },
    { type:"line", who:"narrator", text:"——我用我剩下的细胞，让你长大了。" },
    { type:"line", who:"narrator", text:"——我没办法给你我的记忆。" },
    { type:"line", who:"narrator", text:"——但我希望你能替我做一件事——" },
    { type:"line", who:"narrator", text:"——替我，再叫他一声「哥」。" },
    { type:"line", who:"narrator", text:"——替我，看完他想看的那段未来。" },
    { type:"line", who:"narrator", text:"——他这个人，傻。" },
    { type:"line", who:"narrator", text:"——你别让他一个人守夜。" },
    { type:"player_silhouette", text:"（——你的剪影站在信纸前。手指在颤抖。）" },
    { type:"player_reveal" },
    { type:"line", who:"player", text:"……林夕。" },
    { type:"line", who:"player", text:"——我替你做到了。" },

    /* ---------- Ch13 后日谈 ---------- */
    { type:"chapter", day:3, name:"第十三章 · 后日谈", en:"Ch.13 · Aftermath", scene:"deck" },
    { type:"narr", scene:"deck", text:"星舰穿过又一片银河。" },
    { type:"narr", scene:"deck", text:"凌晨 03:00。你和银，第无数次值班。" },
    { type:"line", who:"yin", exp:"smile", scene:"deck", text:"——B-13。" },
    { type:"line", who:"yin", exp:"smile", text:"——今晚 03:17，不会有人敲门了。" },
    { type:"line", who:"player", text:"——为什么？" },
    { type:"line", who:"yin", exp:"smile", text:"——因为门外那些「死人」，都被我们叫醒了。" },
    { type:"line", who:"yin", exp:"smile", text:"——千夜醒了，云璃醒了，林夕……也借你的身体，醒过来了。" },
    { type:"line", who:"yin", exp:"smile", text:"**——下一次相遇，换我替你守夜。**", important:true },
    { type:"end", tag:"HE", title:"两个人守夜",
      en:"Two Keepers · True End",
      body:"03:17。档案库的门外，没有脚步声。\n你和银，并肩坐着。\n他的半生物心，稳定。\n你的右手，握着他的机械右手。\n\n——这一夜，星舰的守夜人，是两个人。\n下一次相遇——你们已经认出彼此。" }
  ];
})();
