/* =====================================================================
 * 千夜线 v6 · 设定一致性修复 + 起承转合扩写 + 关键句标记
 * 13 主线章 + 6 日常 + 2 隐藏 = 21 节点
 * 关键修正：千夜不再"等你想起来"，她是被修复者；玩家是修复师；
 * 林夕真相只在 Ch10/11 集中爆发，前期保持"陌生 - 共鸣 - 怀疑"渐进
 * 关键句用 important:true 标记（每章至多 1 个，红色加粗 + 拾取关键记忆）
 * ====================================================================== */
(function(){
  if (!window.STORY) window.STORY = {};

  /* 覆盖 千夜线 */
  window.STORY.qianye = [

    /* =========================================================
     *                       Day 1
     * ========================================================= */

    /* ---------- Ch1 苏醒（含倒计时） ---------- */
    { type:"chapter", day:1, name:"第一章 · 苏醒", en:"Ch.1 · Awakening", scene:"deck" },
    { type:"narr", scene:"deck", text:"星舰「忘川号」缓慢驶过仙女座边缘。这是它第 196 次苏醒。" },
    { type:"narr", scene:"deck", text:"舰桥上的全息屏在闪动——红色警告：M-? 级记忆体亟待修复。" },
    { type:"narr", scene:"deck", text:"档案号 A-07 ：千夜 / 女 / 28 岁 / 12 年前自愿封存 / 当前状态——记忆碎片化。" },
    { type:"narr", scene:"deck", text:"系统给你的工作牌上烫着一个名字。但中段几个字符空白。" },
    { type:"line", who:"narrator", text:"修复师，请戴上神经接口。倒计时开始。" },
    { type:"narr", scene:"deck", fx:"flash", text:"接入完成的瞬间，你听到一个女声——清冷，像冬天的窗。" },
    { type:"line", who:"qianye", exp:"calm", scene:"deck", text:"……你来了。" },
    { type:"line", who:"qianye", exp:"calm", text:"我又被唤醒了一次。" },
    { type:"line", who:"qianye", exp:"calm", text:"这是第几次？我不知道。胶囊里没有日历。" },
    { type:"line", who:"qianye", exp:"calm", text:"——但我知道又有一位修复师上岗了。" },
    { type:"line", who:"qianye", exp:"calm", text:"系统说你的编号是 M-□□-□□。中段缺四位。" },
    { type:"line", who:"qianye", exp:"calm", text:"……不奇怪。每一任修复师都有自己的小毛病。" },
    { type:"line", who:"player", text:"（眼前慢慢成像。她坐在椭圆胶囊里，手交叠放在膝上，像在面试自己的命运。）" },
    { type:"line", who:"player", text:"（她抬起眼。瞳色是接近石青的灰蓝。）" },
    { type:"line", who:"qianye", exp:"calm", text:"我先做一个测试。请你回答——重力加速度是多少？" },
    { type:"line", who:"qianye", exp:"calm", text:"我会数到六。" },
    { type:"line", who:"player", text:"（你发现自己心跳变快。这不是常规修复程序里的问题。）" },
    { type:"line", who:"qianye", exp:"calm", text:"……一。" },
    { type:"line", who:"qianye", exp:"calm", text:"……二。" },
    { type:"countdown", text:"她的睫毛在发光。请在 6 秒内回答——重力加速度。", seconds:6,
      options:[
        { text:"9.81 m/s²。", success:true, flag:"countdown_pass", aff:{qianye:2}, next:"q_ch1_after_resp" },
        { text:"……我不太确定。", success:false, aff:{qianye:-1}, next:"q_ch1_after_resp" },
        { text:"（保持沉默）", timeout:true, success:false, aff:{qianye:-3}, flag:"countdown_fail", next:"q_ch1_after_resp" }
      ]
    },
    { type:"label", id:"q_ch1_after_resp" },
    { type:"line", who:"qianye", exp:"smile", scene:"deck", text:"——好。" },
    { type:"line", who:"qianye", exp:"calm", text:"我没有要刁难你。" },
    { type:"line", who:"qianye", exp:"calm", text:"我只是想测一下「会读这个数的人」是不是依旧存在于人间。" },
    { type:"line", who:"player", text:"……什么意思？" },
    { type:"line", who:"qianye", exp:"calm", text:"12 年前，9.81 是我和某个人之间的暗号。" },
    { type:"line", who:"qianye", exp:"calm", text:"你能在 6 秒内说出来——证明你脑子里某个区域比你记得的要清醒。" },
    { type:"line", who:"qianye", exp:"calm", text:"——我们慢慢来。" },
    { type:"narr", scene:"deck", text:"她朝你微微点头。冰凉的胶囊壁映出她肩头淡淡的光。" },
    { type:"line", who:"qianye", exp:"calm", text:"你叫修复师，对吗。" },
    { type:"line", who:"player", text:"……是。" },
    { type:"line", who:"qianye", exp:"calm", text:"那么修复师，欢迎登舰。" },
    { type:"line", who:"qianye", exp:"calm", text:"——别急着拆我。" },
    { type:"line", who:"qianye", exp:"smile", text:"先把我重新装好。" , important:true },
    { type:"line", who:"player", text:"（你不知道为什么——你把这句话当真了。）" },

    /* ---------- Ch2 三件事（含选择 + 二级分支） ---------- */
    { type:"chapter", day:1, name:"第二章 · 三件事", en:"Ch.2 · Three Things", scene:"deck" },
    { type:"narr", scene:"deck", text:"她说，要让你在第一次见面就记住她——必须告诉你三件事。" },
    { type:"line", who:"qianye", exp:"calm", scene:"deck", text:"修复师，我有三件事必须先告诉你。" },
    { type:"line", who:"qianye", exp:"calm", text:"第一件——我曾经不允许我研究室里出现奶糖。" },
    { type:"line", who:"qianye", exp:"calm", text:"因为奶糖会让我想起某个人，而我不允许那个人扰乱我的实验。" },
    { type:"line", who:"qianye", exp:"calm", text:"第二件——我每天读三本书的第 2.46 页。" },
    { type:"line", who:"qianye", exp:"calm", text:"——这个数字没有意义。我只是觉得它好看。" },
    { type:"line", who:"qianye", exp:"sad", text:"第三件……我不能告诉你。" },
    { type:"line", who:"qianye", exp:"sad", text:"如果我现在告诉你，你的修复程序就要重置。" , important:true },
    { type:"line", who:"player", text:"……为什么。" },
    { type:"line", who:"qianye", exp:"calm", text:"因为「第三件」是关于你的。" },
    { type:"line", who:"player", text:"（你愣了一下。胸口某个地方钝钝地动了一下。）" },
    { type:"line", who:"qianye", exp:"calm", text:"你现在可以告诉我，你接下来想问什么。" },
    { type:"choice", options:[
      { text:"我想知道第三件事。", aff:{qianye:2}, flag:"care_third", next:"q_ch2_a" },
      { text:"那让我们先聊别的——比如奶糖。", aff:{qianye:1}, next:"q_ch2_b1" },
      { text:"为什么是「2.46」？", aff:{qianye:3}, flag:"insight_q", next:"q_ch2_b" }
    ]},
    { type:"label", id:"q_ch2_a" },
    { type:"line", who:"qianye", exp:"sad", text:"……我猜你会先问这一件。" },
    { type:"line", who:"qianye", exp:"sad", text:"但我说过，告诉你，你的程序就会重置。" },
    { type:"line", who:"qianye", exp:"calm", text:"那么这次——我用「我不告诉」来回应你。" },
    { type:"line", who:"qianye", exp:"calm", text:"等你修复进度过了 30%，我再告诉你一半。" },
    { type:"jump", to:"q_ch2_main" },
    { type:"label", id:"q_ch2_b1" },
    { type:"line", who:"qianye", exp:"smile", text:"……奶糖是个奇怪的诱饵。" },
    { type:"line", who:"qianye", exp:"smile", text:"它会让一个理性的人，瞬间退化成 5 岁。" },
    { type:"line", who:"qianye", exp:"calm", text:"也许这正是我害怕的。" },
    { type:"jump", to:"q_ch2_main" },
    { type:"label", id:"q_ch2_b" },
    { type:"line", who:"qianye", exp:"blush", text:"……你居然问的是这个。" },
    { type:"line", who:"qianye", exp:"calm", text:"2 是因为它是「最小的偶数」——稳定、平衡。" },
    { type:"line", who:"qianye", exp:"calm", text:"4 是因为它在我研究的张量场中是基准维度。" },
    { type:"line", who:"qianye", exp:"calm", text:"6 是因为我哥哥说我做事「6 分谨慎」。" },
    { type:"line", who:"qianye", exp:"smile", text:"所以是 2.46。这是我私人的小数字。" },
    { type:"line", who:"qianye", exp:"smile", text:"修复师，你是我在 12 年里第一个问我这个数字的人。" },
    { type:"line", who:"player", text:"（这一句让你心里某根弦松了一下。）" },
    { type:"jump", to:"q_ch2_main" },
    { type:"label", id:"q_ch2_main" },
    { type:"line", who:"qianye", exp:"calm", text:"那么，下一个问题——你今晚能陪我多久？" },
    { type:"choice", options:[
      { text:"今晚我就在这里。", aff:{qianye:1}, next:"q_ch2_close" },
      { text:"修复师不应该陪。", aff:{qianye:0}, next:"q_ch2_close" },
      { text:"想陪你多久就多久。", aff:{qianye:2}, flag:"flirt_q", next:"q_ch2_close" }
    ]},
    { type:"label", id:"q_ch2_close" },
    { type:"line", who:"qianye", exp:"calm", text:"……好。那今晚的修复，从灯光开始。" },
    { type:"line", who:"qianye", exp:"calm", text:"请把这一区的灯调到 38%。" },
    { type:"line", who:"qianye", exp:"calm", text:"我喜欢这个亮度。" },
    { type:"line", who:"player", text:"（你照做。屏幕上的数字停在 38%。她垂下眼，像一头终于安静下来的小兽。）" },

    /* ---------- Ch3 空白工号（触摸） ---------- */
    { type:"chapter", day:1, name:"第三章 · 空白工号", en:"Ch.3 · The Blank Number", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"凌晨。星舰的走廊里，全息夜灯只有 30%。" },
    { type:"narr", scene:"corridor", text:"她从胶囊里走出来——这是她 12 年来第二次「站立」。" },
    { type:"line", who:"qianye", exp:"calm", scene:"corridor", text:"修复师，我看你的工作牌。" },
    { type:"line", who:"qianye", exp:"calm", text:"M 开头，这是修复师的代号。" },
    { type:"line", who:"qianye", exp:"calm", text:"但中间四位——M-XX-XX——空着。" },
    { type:"line", who:"qianye", exp:"calm", text:"按理说每一个修复师，编号都唯一不可能空白。" },
    { type:"line", who:"player", text:"……我也注意到了。" },
    { type:"line", who:"qianye", exp:"calm", text:"那么——这是系统问题，还是你的问题？" },
    { type:"line", who:"player", text:"我不知道。" },
    { type:"line", who:"qianye", exp:"calm", text:"那让我看看。" },
    { type:"line", who:"qianye", exp:"calm", text:"——你愿意被我看清楚一点吗？" },
    { type:"touch",
      text:"她伸出手，等你允许她触碰你的工作牌。请轻轻指引她。",
      img:"assets/portraits/qianye.png",
      hint:"摸她的手会传递信号；摸她的额头会让她安静；摸她肩膀会让她明白你的距离",
      regions:[
        { x:50, y:18, r:8, label:"额头", flag:"touch_top", aff:{qianye:1}, next:"q_ch3_touch_after" },
        { x:50, y:52, r:9, label:"手", flag:"touch_hand", aff:{qianye:3}, next:"q_ch3_touch_after" },
        { x:50, y:74, r:9, label:"肩", flag:"touch_shoulder", aff:{qianye:1}, next:"q_ch3_touch_after" }
      ]
    },
    { type:"label", id:"q_ch3_touch_after" },
    { type:"line", who:"qianye", exp:"blush", text:"……" },
    { type:"line", who:"qianye", exp:"calm", text:"你的体温比我想象的高。" },
    { type:"line", who:"qianye", exp:"calm", text:"——但你的工作牌没有任何反应。" },
    { type:"line", who:"qianye", exp:"calm", text:"系统不能识别你的中段编号。" },
    { type:"line", who:"qianye", exp:"sad", text:"修复师，你是不是知道你的中段编号是什么？" },
    { type:"choice", options:[
      { text:"我从来没见过自己的完整编号。", aff:{qianye:1}, next:"q_ch3_after" },
      { text:"我不知道为什么是空的。", aff:{qianye:1}, next:"q_ch3_after" },
      { text:"我也想知道。但说实话——我害怕知道。", aff:{qianye:3}, flag:"honest_q", next:"q_ch3_after" }
    ]},
    { type:"label", id:"q_ch3_after" },
    { type:"line", who:"qianye", exp:"calm", text:"……害怕。" },
    { type:"line", who:"qianye", exp:"calm", text:"我喜欢你说出这个词。" },
    { type:"line", who:"qianye", exp:"calm", text:"理性的人，从来不轻易说害怕。" },
    { type:"line", who:"qianye", exp:"calm", text:"——除非他知道，他害怕的是什么。" },
    { type:"line", who:"player", text:"……我不知道。但每次看你，我有个不属于我的画面在闪。" },
    { type:"line", who:"qianye", exp:"calm", text:"什么画面。" },
    { type:"line", who:"player", text:"……一个穿白大褂的女人，在写一组很长的方程式。" },
    { type:"line", who:"player", text:"她的笔尖在「9.81」上停留了 0.5 秒。" },
    { type:"line", who:"qianye", exp:"sad", text:"……" },
    { type:"line", who:"qianye", exp:"sad", text:"那是——12 年前的我。" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师，你脑子里——好像偶尔会闪过一些不属于你的画面。" },
    { type:"line", who:"qianye", exp:"calm", text:"这种现象在修复师身上不算罕见。" },
    { type:"line", who:"qianye", exp:"calm", text:"——是被修复者的记忆碎片，因为接口没收紧而漏到你这边。" , important:true },
    { type:"line", who:"qianye", exp:"calm", text:"我会比下一任，更努力地把碎片守住。" },

    /* ---------- Ch4 第一杯咖啡（拖拽） ---------- */
    { type:"chapter", day:1, name:"第四章 · 第一杯咖啡", en:"Ch.4 · The First Coffee", scene:"cabin" },
    { type:"narr", scene:"cabin", text:"傍晚。她说她没喝咖啡 12 年了。" },
    { type:"narr", scene:"cabin", text:"——「没法喝」和「不想喝」是两件事。她属于前者。" },
    { type:"line", who:"qianye", exp:"smile", scene:"cabin", text:"修复师，给我配一杯。" },
    { type:"line", who:"player", text:"我自己来配？" },
    { type:"line", who:"qianye", exp:"smile", text:"你以为我会让你看着我配吗？" },
    { type:"line", who:"qianye", exp:"smile", text:"——你来。我看你。" },
    { type:"line", who:"qianye", exp:"calm", text:"我以前最爱的配方——3 浓缩 + 1 牛奶 + 1 糖。三比一比一。" },
    { type:"line", who:"qianye", exp:"calm", text:"但你听到我说的是这个比例之前——选你自己想配的。" },
    { type:"line", who:"qianye", exp:"calm", text:"你不是来执行命令的修复师。" },
    { type:"line", who:"qianye", exp:"calm", text:"你是来帮我把零碎的「我」重新拼回去的人。" , important:true },
    { type:"drag",
      text:"把配料拖入正确的格子，做一杯她可能喜欢的咖啡。",
      hint:"她说过 3:1:1（浓缩 / 牛奶 / 糖）",
      items:[
        { label:"浓缩 ×3" }, { label:"牛奶 ×1" }, { label:"糖 ×1" },
        { label:"白兰地" }, { label:"焦糖" }
      ],
      targets:[
        { id:"main", label:"主体" },
        { id:"sub",  label:"中和" },
        { id:"sweet", label:"甜味" }
      ],
      answer:{ "0":"main", "1":"sub", "2":"sweet" },
      success:{ flag:"coffee_b", aff:{qianye:3}, next:"q_ch4_perfect" },
      fail:{ flag:"coffee_off", aff:{qianye:0}, next:"q_ch4_off" }
    },
    { type:"label", id:"q_ch4_perfect" },
    { type:"line", who:"qianye", exp:"calm", text:"……" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师，你是不是听过我配的咖啡？" },
    { type:"line", who:"player", text:"……没有。我只是按你说的比例来的。" },
    { type:"line", who:"qianye", exp:"smile", text:"那是巧合。" },
    { type:"line", who:"qianye", exp:"smile", text:"但我喜欢这个巧合。" },
    { type:"line", who:"qianye", exp:"smile", text:"这是 12 年前我自己配的最后一杯。" },
    { type:"line", who:"qianye", exp:"blush", text:"修复师，你的手指——是会记得的。" },
    { type:"line", who:"player", text:"（你低头看自己的手。指尖确实有某种残留的肌肉记忆——握杯柄的角度恰到好处。）" },
    { type:"line", who:"player", text:"（但你不知道这是从何而来。）" },
    { type:"jump", to:"q_ch4_close" },
    { type:"label", id:"q_ch4_off" },
    { type:"line", who:"qianye", exp:"calm", text:"……" },
    { type:"line", who:"qianye", exp:"smile", text:"也行。新的口味。" },
    { type:"line", who:"qianye", exp:"smile", text:"我现在是新的人。" },
    { type:"line", who:"qianye", exp:"calm", text:"或者说——我希望我是。" },
    { type:"label", id:"q_ch4_close" },
    { type:"narr", scene:"cabin", text:"她接过杯子。指尖和你的指尖相碰，0.4 秒。" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师。" },
    { type:"line", who:"qianye", exp:"calm", text:"我决定告诉你——「第三件事」的一半。" },
    { type:"line", who:"qianye", exp:"sad", text:"我十二年前自愿封存自己的原因——是因为我做过一个实验失败了。" },
    { type:"line", who:"qianye", exp:"sad", text:"实验对象不是我自己，是另一个我很重要的人。" },
    { type:"line", who:"qianye", exp:"sad", text:"——但今天就讲到这里。再讲下去，你的程序会触发。" },
    { type:"cg", id:"qianye_cg1", title:"第一杯咖啡", scene:"cabin", img:"qianye_d1" },
    { type:"mail", id:"sys_d1", role:"system", title:"修复师 · 日报", body:"Day 1 完成。A-07 修复进度：8% → 12%。\n\n附：你的工作牌中段编号缺失，已上报维护组。\n附二：A-07 在最近 3 小时心率峰值出现 6 次。建议：明日继续。" },
    { type:"narr", text:"=== Day 1 主线结束 ===" },

    /* ---------- 日常 1：星图笔记 ---------- */
    { type:"chapter", day:1, name:"日常 · 星图笔记", en:"Daily · Star Notebook", scene:"cabin" },
    { type:"narr", scene:"cabin", text:"她送你一本陈旧的笔记本。封皮是深灰色——边角磨损得像被反复抚摸。" },
    { type:"line", who:"qianye", exp:"calm", scene:"cabin", text:"我醒来时口袋里就有这个。" },
    { type:"line", who:"qianye", exp:"calm", text:"扉页那行字——我看不清。" },
    { type:"line", who:"qianye", exp:"calm", text:"它好像是被人擦过。又像是被时间自己擦掉的。" },
    { type:"line", who:"player", text:"我能翻一下吗。" },
    { type:"line", who:"qianye", exp:"calm", text:"嗯。" },
    { type:"narr", scene:"cabin", text:"内页是一片片星图——她随手画的。每一颗都标着一个让你莫名其妙的小数字。" },
    { type:"line", who:"player", text:"……这些小数字是什么。" },
    { type:"line", who:"qianye", exp:"smile", text:"距离。每一颗星到我那年研究室门口的距离。" },
    { type:"line", who:"qianye", exp:"smile", text:"——这就是我的小爱好。" },
    { type:"line", who:"player", text:"（你停在第 14 页。）" },
    { type:"line", who:"player", text:"（这一页中央被一只钢笔点了一个小黑点。旁边写着「9.81」。）" },
    { type:"choice", options:[
      { text:"让我看看扉页。", aff:{qianye:1}, next:"q_d1_note_a" },
      { text:"也许故意被擦掉。", aff:{qianye:1}, flag:"erased_q", next:"q_d1_note_a" },
      { text:"不要看了。属于你的，让你自己慢慢想起来。", aff:{qianye:3}, flag:"respect_q", next:"q_d1_note_b" }
    ]},
    { type:"label", id:"q_d1_note_a" },
    { type:"line", who:"player", text:"（你侧着光看，隐约是一个名字——林.夕？还是别的什么？）" },
    { type:"line", who:"player", text:"（但笔迹被一道横线划掉，留下一个小小的擦痕。）" },
    { type:"line", who:"qianye", exp:"calm", text:"……如果你看清了，告诉我。" },
    { type:"line", who:"qianye", exp:"calm", text:"我不会因为它伤心。我只想知道。" },
    { type:"jump", to:"q_d1_note_close" },
    { type:"label", id:"q_d1_note_b" },
    { type:"line", who:"qianye", exp:"blush", text:"……" },
    { type:"line", who:"qianye", exp:"blush", text:"谢谢。" },
    { type:"line", who:"qianye", exp:"smile", text:"我会想起来的。等我想起来的那天，我先告诉你。" },
    { type:"line", who:"qianye", exp:"smile", text:"在我之前任何人之前——我先告诉你。" , important:true },
    { type:"label", id:"q_d1_note_close" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师，今晚睡前——把灯关到 12%。" },
    { type:"line", who:"qianye", exp:"calm", text:"我喜欢能勉强看见你脸轮廓的那个亮度。" },
    { type:"narr", scene:"cabin", text:"她翻到笔记本中段。" },
    { type:"narr", scene:"cabin", text:"——一张孤零零的小纸条，被胶带粘在那一页中央。" },
    { type:"line", who:"qianye", exp:"calm", text:"这是 12 年前我做实验那天写的。" },
    { type:"line", who:"qianye", exp:"calm", text:"上面写：「如果实验失败，请把我封存。」" },
    { type:"line", who:"qianye", exp:"calm", text:"「如果实验成功——请把我修复。」" },
    { type:"line", who:"qianye", exp:"sad", text:"现在的情况是——两个都不算。" },
    { type:"line", who:"qianye", exp:"sad", text:"实验既没成功，也没完全失败。" },
    { type:"line", who:"qianye", exp:"sad", text:"所以我醒着，但我不完整。" },
    { type:"line", who:"player", text:"……所以你就在这里等？" },
    { type:"line", who:"qianye", exp:"calm", text:"不是等。是——存放。" },
    { type:"line", who:"qianye", exp:"smile", text:"等待会让人焦虑。存放只需要一个数字——196。" },
    { type:"line", who:"qianye", exp:"calm", text:"196 次苏醒，对应 196 次「重新一遍」。" },
    { type:"line", who:"qianye", exp:"calm", text:"——但这一次，我决定记住你。" },
    { type:"line", who:"qianye", exp:"smile", text:"修复师，谢谢你今天没有像其他人那样把我「按部就班」地处理。" },
    { type:"line", who:"player", text:"（你不知道她说的「其他人」是谁。但你听出了温度。）" },

    /* ---------- 日常 2：失眠夜（触摸） ---------- */
    { type:"chapter", day:1, name:"日常 · 失眠夜", en:"Daily · Sleepless", scene:"cabin" },
    { type:"narr", scene:"cabin", text:"凌晨 2:47。" },
    { type:"narr", scene:"cabin", text:"星舰外的虚空在缓慢呼吸。她的语音通话忽然来了。" },
    { type:"line", who:"qianye", exp:"sad", text:"……修复师，我睡不着。" },
    { type:"line", who:"qianye", exp:"sad", text:"每次闭眼，都像在重新进入胶囊。" },
    { type:"line", who:"qianye", exp:"sad", text:"——你那边几点。" },
    { type:"line", who:"player", text:"……和你一样。" },
    { type:"choice", options:[
      { text:"开视频，让我看到你。", aff:{qianye:2}, next:"q_d1_sleep_video" },
      { text:"我去你那。", aff:{qianye:3}, flag:"physical_q", next:"q_d1_sleep_visit" },
      { text:"数 9.81 个数。", aff:{qianye:3}, flag:"witty_q", next:"q_d1_sleep_count" }
    ]},
    { type:"label", id:"q_d1_sleep_video" },
    { type:"line", who:"qianye", exp:"smile", text:"……你这副刚被吵醒的样子很难看。" },
    { type:"line", who:"qianye", exp:"smile", text:"但很可爱。" },
    { type:"line", who:"qianye", exp:"smile", text:"我把摄像头朝着窗外。看，外面正过一颗失败的小行星。" },
    { type:"line", who:"player", text:"……失败的小行星？" },
    { type:"line", who:"qianye", exp:"calm", text:"它本来要变成行星的。但它停在某个质量不上不下的位置。" },
    { type:"line", who:"qianye", exp:"calm", text:"它就一直在那。" },
    { type:"line", who:"qianye", exp:"sad", text:"——很多人也是这样。" },
    { type:"jump", to:"q_d1_sleep_close" },
    { type:"label", id:"q_d1_sleep_visit" },
    { type:"line", who:"qianye", exp:"blush", text:"……" },
    { type:"line", who:"qianye", exp:"blush", text:"门没锁。" },
    { type:"narr", scene:"cabin", text:"她的舱内只有床头一盏蓝光。她背对着你，肩头微微缩起。" },
    { type:"touch",
      text:"她在颤抖。你想做什么？",
      img:"assets/portraits/qianye_sad.png",
      hint:"不必每次都做选择，有时候只是一个动作",
      regions:[
        { x:50, y:22, r:9, label:"摸头", flag:"touch_head", aff:{qianye:2}, next:"q_d1_sleep_touch_after" },
        { x:50, y:52, r:9, label:"握手", flag:"touch_hand", aff:{qianye:3}, next:"q_d1_sleep_touch_after" },
        { x:50, y:75, r:9, label:"轻拍肩", flag:"touch_shoulder", aff:{qianye:2}, next:"q_d1_sleep_touch_after" }
      ]
    },
    { type:"label", id:"q_d1_sleep_touch_after" },
    { type:"line", who:"qianye", exp:"blush", text:"……我可以靠一下吗。" },
    { type:"line", who:"player", text:"（她什么都没说，但你已经把头借给她。）" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师……" },
    { type:"line", who:"qianye", exp:"calm", text:"等会儿我可能会做梦。" },
    { type:"line", who:"qianye", exp:"calm", text:"我做梦的时候，会念一个名字。" },
    { type:"line", who:"qianye", exp:"sad", text:"——你不要走，也不要回应。" , important:true },
    { type:"line", who:"qianye", exp:"sad", text:"听完就好。" },
    { type:"jump", to:"q_d1_sleep_close" },
    { type:"label", id:"q_d1_sleep_count" },
    { type:"line", who:"qianye", exp:"smile", text:"……一……二……" },
    { type:"line", who:"qianye", exp:"smile", text:"……数到 6 的时候我已经睡着了。" },
    { type:"line", who:"qianye", exp:"smile", text:"修复师，你这个建议——很多余。" },
    { type:"line", who:"qianye", exp:"smile", text:"但我喜欢。" },
    { type:"label", id:"q_d1_sleep_close" },
    { type:"narr", text:"=== 日常结束 ===" },

    /* =========================================================
     *                       Day 2
     * ========================================================= */

    /* ---------- Ch5 雨中花园（QTE） ---------- */
    { type:"chapter", day:2, name:"第五章 · 雨中花园", en:"Ch.5 · Rain in the Garden", scene:"garden" },
    { type:"narr", scene:"garden", fx:"rain", text:"全息花园 · 雨。雨落在皮肤上是温的，因为这是模拟。" },
    { type:"narr", scene:"garden", fx:"rain", text:"她穿着白色斗篷，站在一棵会开蓝花的全息柳下。" },
    { type:"line", who:"qianye", exp:"calm", scene:"garden", fx:"rain", text:"修复师，你听过雨声里藏的歌吗？" },
    { type:"line", who:"player", text:"……雨声里能藏歌？" },
    { type:"line", who:"qianye", exp:"smile", text:"嗯。" },
    { type:"line", who:"qianye", exp:"smile", text:"如果雨点的频率是 2.46 Hz，你会听到一段旋律。" },
    { type:"line", who:"qianye", exp:"smile", text:"我曾经把整个春天的雨声都做成磁带。" },
    { type:"line", who:"qianye", exp:"smile", text:"现在我哼一段，你跟拍——能跟上的话，我送你一颗记忆碎片。" },
    { type:"qte",
      text:"千夜在雨里哼歌。跟着她的节拍，按下「击中」。",
      beats:6,
      intervalMs:1100,
      success:{ flag:"mini_qy_perfect", aff:{qianye:3}, next:"q_ch5_qte_pass" },
      fail:{ flag:"mini_qy_fail", aff:{qianye:0}, next:"q_ch5_qte_miss" }
    },
    { type:"label", id:"q_ch5_qte_pass" },
    { type:"line", who:"qianye", exp:"smile", text:"……你怎么会跟拍？" },
    { type:"line", who:"qianye", exp:"smile", text:"这是我研究室里只放给一个人听过的旋律。" },
    { type:"line", who:"player", text:"（你不知道为什么会跟。但你知道这件事。）" },
    { type:"line", who:"player", text:"（你的脚趾头按得很自然——左 / 右 / 左左 / 右。）" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师，你的身体——比你的脑子诚实。" },
    { type:"jump", to:"q_ch5_after_qte" },
    { type:"label", id:"q_ch5_qte_miss" },
    { type:"line", who:"qianye", exp:"calm", text:"……没关系。" },
    { type:"line", who:"qianye", exp:"smile", text:"也许你以后会记得。" },
    { type:"label", id:"q_ch5_after_qte" },
    { type:"narr", scene:"garden", fx:"rain", text:"她从斗篷下取出一支笔。笔身是哑光银，笔帽上有半个月亮的刻痕。" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师，你戴过眼镜吗？" },
    { type:"line", who:"player", text:"……？没戴过。" },
    { type:"line", who:"qianye", exp:"sad", text:"奇怪。我看你的时候，总觉得你眼睛被某种镜片折射过。" },
    { type:"line", who:"qianye", exp:"sad", text:"——我曾经送给一个人这样一支笔。" },
    { type:"line", who:"qianye", exp:"sad", text:"他喜欢戴半月形的银边眼镜。" },
    { type:"line", who:"qianye", exp:"sad", text:"——这是我们俩的暗号。" },
    { type:"line", who:"player", text:"（你低头看自己的鼻梁。没有镜架的痕迹。）" },
    { type:"line", who:"player", text:"（但你的指节自动曲起来——像在扶起一副不存在的眼镜。）" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师，你刚刚做的那个动作。" },
    { type:"line", who:"qianye", exp:"calm", text:"——是他的动作。" , important:true },
    { type:"line", who:"player", text:"……他是谁。" },
    { type:"line", who:"qianye", exp:"calm", text:"以后再说。" },
    { type:"line", who:"qianye", exp:"calm", text:"——你今天还需要陪我走 20 分钟。" },
    { type:"narr", scene:"garden", fx:"rain", text:"全息雨变小。她伸手接住一颗。" },
    { type:"line", who:"qianye", exp:"smile", text:"修复师。雨停之前我有一个不情之请。" },
    { type:"line", who:"qianye", exp:"smile", text:"——以后能不能不要叫我「A-07」？" },
    { type:"line", who:"qianye", exp:"calm", text:"那是档案号。我有名字。" },
    { type:"line", who:"player", text:"……千夜。" },
    { type:"line", who:"qianye", exp:"smile", text:"嗯。" },
    { type:"line", who:"qianye", exp:"smile", text:"修复师叫我千夜——比叫我 A-07 让我多 6 分活的实感。" },
    { type:"line", who:"player", text:"（你忽然想——你的工作牌上，那个被空掉的名字，到底是什么？）" },

    /* ---------- Ch6 信任考验（打字） ---------- */
    { type:"chapter", day:2, name:"第六章 · 信任考验", en:"Ch.6 · The Vow", scene:"garden" },
    { type:"narr", scene:"garden", text:"她让你坐在一张长椅上。她把那支笔放在你掌心。" },
    { type:"line", who:"qianye", exp:"calm", scene:"garden", text:"修复师，我现在要请你做一件事。" },
    { type:"line", who:"qianye", exp:"calm", text:"我把那句不知道是谁对我说的话，让你亲手写一遍。" },
    { type:"line", who:"qianye", exp:"sad", text:"如果是你写的，我会知道。" },
    { type:"line", who:"qianye", exp:"sad", text:"如果不是你写的，那就当我自言自语。" },
    { type:"line", who:"player", text:"……什么句子。" },
    { type:"line", who:"qianye", exp:"calm", text:"——请你现在开始写。" },
    { type:"line", who:"qianye", exp:"calm", text:"如果你的手知道答案，它会自己写出来。" },
    { type:"typing",
      text:"亲手把她的那句话写下来。",
      prompt:"答应我，下一次相遇，你要先认出我。",
      answer:"答应我，下一次相遇，你要先认出我。",
      tolerance:4,
      hint:"输入完成后按 Enter 或回车",
      success:{ flag:"vow_typed", aff:{qianye:4}, next:"q_ch6_vow_pass" },
      fail:{ flag:"vow_failed", aff:{qianye:-1}, next:"q_ch6_vow_fail" }
    },
    { type:"label", id:"q_ch6_vow_pass" },
    { type:"line", who:"qianye", exp:"blush", text:"……" },
    { type:"line", who:"qianye", exp:"blush", text:"修复师……" },
    { type:"line", who:"qianye", exp:"blush", text:"我今天不打算再叫你修复师了。" },
    { type:"line", who:"player", text:"那叫我什么？" },
    { type:"line", who:"qianye", exp:"calm", text:"——我还在想。" },
    { type:"line", who:"qianye", exp:"smile", text:"也许下一章，我会想出来。" },
    { type:"line", who:"qianye", exp:"smile", text:"但你刚刚写下的那一句——是 12 年前我的最后一句话。" , important:true },
    { type:"line", who:"qianye", exp:"sad", text:"我以为我会一个人带着这句话走完所有时间线。" },
    { type:"line", who:"qianye", exp:"sad", text:"——结果你来了。" },
    { type:"jump", to:"q_ch6_close" },
    { type:"label", id:"q_ch6_vow_fail" },
    { type:"line", who:"qianye", exp:"sad", text:"……不是这一句。" },
    { type:"line", who:"qianye", exp:"sad", text:"也对，凭什么是你呢。" },
    { type:"line", who:"qianye", exp:"calm", text:"——但谢谢你试了。" },
    { type:"line", who:"qianye", exp:"calm", text:"试，是诚意的最低标准。" },
    { type:"label", id:"q_ch6_close" },
    { type:"cg", id:"qianye_cg2", title:"全息雨中的承诺", scene:"garden", img:"qianye_d2" },

    /* ---------- Ch7 共同回忆（滑动） ---------- */
    { type:"chapter", day:2, name:"第七章 · 共同回忆", en:"Ch.7 · Shared Memory", scene:"cabin" },
    { type:"narr", scene:"cabin", text:"她在你面前坐下。她的额发遮住了大半边脸。" },
    { type:"line", who:"qianye", exp:"calm", scene:"cabin", text:"我醒来后，第一次照镜子，发现额头有一道疤。" },
    { type:"line", who:"qianye", exp:"calm", text:"我不记得是哪里来的。" },
    { type:"line", who:"qianye", exp:"calm", text:"——但每次我用手摸到它，我会想起一种水泥的味道。" },
    { type:"line", who:"player", text:"水泥……？" },
    { type:"line", who:"qianye", exp:"calm", text:"和阳光晒过之后那种灰色的、有点甜的气味。" },
    { type:"line", who:"qianye", exp:"calm", text:"它和我哥哥的童年有关。" },
    { type:"line", who:"qianye", exp:"blush", text:"修复师……你帮我看看。" },
    { type:"swipe",
      text:"慢慢拨开她额前的发帘。",
      direction:"left",
      dirHint:"向左滑",
      reveal:"assets/cg/qianye_he.png",
      success:{ flag:"scar_seen", aff:{qianye:3}, next:"q_ch7_scar_seen" },
      fail:{ next:"q_ch7_scar_miss" }
    },
    { type:"label", id:"q_ch7_scar_seen" },
    { type:"line", who:"player", text:"（一道横在左额的浅疤，形状像一道阶梯。）" },
    { type:"line", who:"player", text:"（你心里「咔」地一声——这是你小时候和你妹妹打闹留的疤。）" },
    { type:"line", who:"player", text:"（不对——是和「哥哥」？还是「妹妹」？……你也分不清了。）" },
    { type:"anomaly", text:"⚠ 玩家身份耦合度 +20% · clue_scar 解锁", clue:"clue_scar" },
    { type:"line", who:"qianye", exp:"sad", text:"看到了？" },
    { type:"line", who:"player", text:"……看到了。" },
    { type:"line", who:"qianye", exp:"sad", text:"那你愿意告诉我，是怎么留的吗？" },
    { type:"choice", options:[
      { text:"是和你妹妹打闹的时候，你撞到楼梯。", aff:{qianye:3}, flag:"truth_scar", next:"q_ch7_after_scar" },
      { text:"我不知道。但我会帮你查清楚。", aff:{qianye:1}, next:"q_ch7_after_scar" },
      { text:"对不起，我说不出口。", aff:{qianye:0}, flag:"choke_q", next:"q_ch7_after_scar" }
    ]},
    { type:"label", id:"q_ch7_after_scar" },
    { type:"line", who:"qianye", exp:"calm", text:"……" },
    { type:"line", who:"qianye", exp:"calm", text:"你说「妹妹」。" },
    { type:"line", who:"qianye", exp:"calm", text:"——我从来没说过我有妹妹。" },
    { type:"line", who:"qianye", exp:"sad", text:"你是怎么知道的？" },
    { type:"line", who:"player", text:"……我也不知道。" },
    { type:"line", who:"qianye", exp:"sad", text:"修复师……" },
    { type:"line", who:"qianye", exp:"sad", text:"你脑子里，有一个我从来没有遇见过的「我」。" , important:true },
    { type:"jump", to:"q_ch7_close" },
    { type:"label", id:"q_ch7_scar_miss" },
    { type:"line", who:"qianye", exp:"sad", text:"……没事。我下次再让你看。" },
    { type:"line", who:"qianye", exp:"calm", text:"也许这是命定要慢一点的。" },
    { type:"label", id:"q_ch7_close" },

    /* ---------- Ch8 重大冲突（倒计时 + BE2） ---------- */
    { type:"chapter", day:2, name:"第八章 · 重大冲突", en:"Ch.8 · Confrontation", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她忽然在走廊拦住你。" },
    { type:"narr", scene:"corridor", text:"她的瞳孔在收缩——这不是她平时的表情。" },
    { type:"line", who:"qianye", exp:"sad", scene:"corridor", text:"修复师。我问你一个问题，请你不要思考超过 3 秒。" },
    { type:"line", who:"qianye", exp:"sad", text:"——你是修复师，还是认识我的人？" , important:true },
    { type:"line", who:"player", text:"（你的胸口忽然一抽。）" },
    { type:"line", who:"player", text:"（——那种感觉像被某个旧的密码本撞开了一格。）" },
    { type:"countdown", text:"她在等你的回答。", seconds:4,
      options:[
        { text:"我是修复师。", success:false, flag:"choice_repair", aff:{qianye:0}, next:"q_ch8_repair" },
        { text:"我是认识你的人。", success:true, flag:"choice_know", aff:{qianye:3}, next:"q_ch8_know" },
        { text:"两个都是。", success:true, flag:"choice_both", aff:{qianye:4}, next:"q_ch8_both" },
        { text:"（沉默）", timeout:true, success:false, flag:"choice_silence", aff:{qianye:-3}, next:"q_ch8_silence" }
      ]
    },
    { type:"label", id:"q_ch8_repair" },
    { type:"line", who:"qianye", exp:"sad", text:"……好。" },
    { type:"line", who:"qianye", exp:"sad", text:"那请保持你的专业距离。" },
    { type:"line", who:"qianye", exp:"calm", text:"修复进度按章节推进。" },
    { type:"line", who:"qianye", exp:"calm", text:"——但请你别再让我做不必要的咖啡测试。" },
    { type:"jump", to:"q_ch8_close" },
    { type:"label", id:"q_ch8_know" },
    { type:"line", who:"qianye", exp:"blush", text:"……" },
    { type:"line", who:"qianye", exp:"blush", text:"我知道。" },
    { type:"line", who:"qianye", exp:"blush", text:"但我希望你亲口说。" },
    { type:"line", who:"qianye", exp:"calm", text:"我也是「亲口说出来才相信」的人。" },
    { type:"jump", to:"q_ch8_close" },
    { type:"label", id:"q_ch8_both" },
    { type:"line", who:"qianye", exp:"smile", text:"……你比我想象中的诚实。" },
    { type:"line", who:"qianye", exp:"smile", text:"——这两个身份，本来就是同一个人的两面。" },
    { type:"line", who:"qianye", exp:"calm", text:"如果你能把它们都接住，你就有资格修复我。" },
    { type:"jump", to:"q_ch8_close" },
    { type:"label", id:"q_ch8_silence" },
    { type:"line", who:"qianye", exp:"sad", text:"……好。" },
    { type:"line", who:"qianye", exp:"sad", text:"那我也保持我的沉默。" },
    { type:"line", who:"qianye", exp:"sad", text:"修复师，请你今天就回报告。" },
    { type:"line", who:"qianye", exp:"sad", text:"案件 A-07，我自己来收尾。" },
    { type:"be", title:"BE2 · 沉默的代价",
      en:"Cost of Silence",
      body:"她回到胶囊。\n你站在走廊里，听见自动门「啪」地一声合上。\n第二天清晨，星舰系统弹出通知：A-07 自愿提前封档。\n——你不会再见到她。\n\n你从此被记录在档案里，作为「无法完成 A-07 修复」的修复师。" },
    { type:"label", id:"q_ch8_close" },
    { type:"narr", text:"=== Day 2 主线结束 ===" },

    /* ---------- 日常 3：送花 ---------- */
    { type:"chapter", day:2, name:"日常 · 送花", en:"Daily · The Flower", scene:"garden" },
    { type:"narr", scene:"garden", text:"花园里有一朵全息蓝花，是稀有品。" },
    { type:"narr", scene:"garden", text:"它每隔 2.46 小时盛开一次。每次只开 6 分钟。" },
    { type:"line", who:"qianye", exp:"calm", scene:"garden", text:"修复师，这朵花——你怎么处理？" },
    { type:"choice", options:[
      { text:"摘下来送给她。", aff:{qianye:2}, gift:"flower", next:"q_d2_flower_a" },
      { text:"留在原处。带她过来看。", aff:{qianye:3}, flag:"share_view", next:"q_d2_flower_b" },
      { text:"自己留着。我也喜欢花。", aff:{qianye:0}, next:"q_d2_flower_c" }
    ]},
    { type:"label", id:"q_d2_flower_a" },
    { type:"line", who:"qianye", exp:"smile", text:"……谢谢。" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师，花最好留在花园。" },
    { type:"line", who:"qianye", exp:"calm", text:"但你舍不得让我走过来——这点心意，我收下。" },
    { type:"jump", to:"q_d2_flower_close" },
    { type:"label", id:"q_d2_flower_b" },
    { type:"line", who:"qianye", exp:"blush", text:"修复师，你让我看花，是不是觉得我也是要被看的？" },
    { type:"line", who:"qianye", exp:"smile", text:"……没事。我让你看了。" },
    { type:"line", who:"qianye", exp:"calm", text:"我看花和花看我，是两件事。" },
    { type:"line", who:"qianye", exp:"calm", text:"你让我去——是把这两件事都还给我。" },
    { type:"jump", to:"q_d2_flower_close" },
    { type:"label", id:"q_d2_flower_c" },
    { type:"line", who:"qianye", exp:"calm", text:"嗯。" },
    { type:"line", who:"qianye", exp:"calm", text:"自私的人比假装慷慨的人，可信一些。" },
    { type:"label", id:"q_d2_flower_close" },

    /* ---------- 日常 4：双人记忆碎片 ---------- */
    { type:"chapter", day:2, name:"日常 · 双人记忆碎片", en:"Daily · Co-op Memory", scene:"cabin" },
    { type:"narr", scene:"cabin", text:"她说她想和你一起玩一个游戏。" },
    { type:"line", who:"qianye", exp:"calm", scene:"cabin", text:"——8 张牌，4 对配对。" },
    { type:"line", who:"qianye", exp:"calm", text:"看看你能不能把我的「记忆碎片」都翻出来。" },
    { type:"choice", options:[
      { text:"来。", aff:{qianye:1}, mini:"qy", next:"q_d2_coop_after" },
      { text:"我们换个安静一点的事情。", aff:{qianye:2}, flag:"quiet_q", next:"q_d2_coop_after" }
    ]},
    { type:"label", id:"q_d2_coop_after" },
    { type:"line", who:"qianye", exp:"calm", text:"修复师，你有没有发现——" },
    { type:"line", who:"qianye", exp:"calm", text:"我让你做的所有「小事」，都是 12 年前我和某个人做过的事情。" },
    { type:"line", who:"qianye", exp:"sad", text:"——抱歉。我只是想确认，你是不是他。" },
    { type:"line", who:"qianye", exp:"sad", text:"你不要回答。我自己会判断。" },
    { type:"narr", text:"=== 日常结束 ===" },

    /* ---------- 隐藏 1：双胞胎记忆 ---------- */
    { type:"chapter", day:2, name:"隐藏 · 双胞胎记忆", en:"Hidden · The Twins", scene:"archive" },
    { type:"narr", scene:"archive", text:"档案库深处。她调出一个尘封文件。" },
    { type:"line", who:"qianye", exp:"sad", scene:"archive", text:"……我有一个双胞胎兄弟。" },
    { type:"line", who:"qianye", exp:"sad", text:"他叫林夕。" },
    { type:"line", who:"qianye", exp:"sad", text:"他在我做实验那年，把自己也送进了胶囊。" },
    { type:"line", who:"qianye", exp:"sad", text:"——他签下的那行字，被刻痕划掉了。" },
    { type:"line", who:"qianye", exp:"calm", text:"我没有去查他被划掉的原因。" },
    { type:"line", who:"qianye", exp:"calm", text:"——因为我害怕看到他自己刻下的「不愿意醒来」这几个字。" },
    { type:"line", who:"player", text:"（你的呼吸——又一次变浅。）" },
    { type:"choice", options:[
      { text:"……他叫什么？再说一次。", aff:{qianye:1}, next:"q_hidden1_a" },
      { text:"他长什么样？", aff:{qianye:2}, flag:"want_to_know_lin", next:"q_hidden1_b" },
      { text:"他是不是……和我有点像？", aff:{qianye:4}, flag:"hint_self_q", next:"q_hidden1_c" }
    ]},
    { type:"label", id:"q_hidden1_a" },
    { type:"line", who:"qianye", exp:"sad", text:"林夕。" },
    { type:"line", who:"qianye", exp:"sad", text:"林。夕。" },
    { type:"line", who:"qianye", exp:"sad", text:"——「夕」不是「夕阳」的夕。" },
    { type:"line", who:"qianye", exp:"sad", text:"是「夕惕若厉」的夕。" },
    { type:"jump", to:"q_hidden1_close" },
    { type:"label", id:"q_hidden1_b" },
    { type:"line", who:"qianye", exp:"sad", text:"和你像。" },
    { type:"line", who:"qianye", exp:"sad", text:"非常非常像。" },
    { type:"line", who:"qianye", exp:"sad", text:"差别只在他左眉骨上有一颗淡红色的痣。" },
    { type:"line", who:"qianye", exp:"sad", text:"——你有吗？" },
    { type:"line", who:"player", text:"（你不敢去摸自己的眉骨。）" },
    { type:"jump", to:"q_hidden1_close" },
    { type:"label", id:"q_hidden1_c" },
    { type:"line", who:"qianye", exp:"blush", text:"……" },
    { type:"line", who:"qianye", exp:"blush", text:"修复师，我现在不敢看你的脸了。" },
    { type:"line", who:"qianye", exp:"sad", text:"我把这个文件设成「只有你能看见」。" },
    { type:"line", who:"qianye", exp:"sad", text:"——你下次自己一个人来翻。" },
    { type:"jump", to:"q_hidden1_close" },
    { type:"label", id:"q_hidden1_close" },
    { type:"anomaly", text:"⚠ 隐藏剧情解锁 · 林夕（玩家本人）", clue:"clue_lin_xi" },

    /* =========================================================
     *                       Day 3
     * ========================================================= */

    /* ---------- Ch9 危机（倒计时 + 拖拽 + BE） ---------- */
    { type:"chapter", day:3, name:"第九章 · 危机", en:"Ch.9 · Crisis", scene:"archive" },
    { type:"narr", scene:"archive", fx:"flash", text:"系统警报：A-07 神经接口故障。10 秒内须修复，否则记忆永久封存。" },
    { type:"narr", scene:"archive", fx:"flash", text:"她的胶囊舱开始降温。胶囊壁内壁结出薄薄的霜花。" },
    { type:"line", who:"qianye", exp:"sad", scene:"archive", text:"修复师……我又开始忘了。" },
    { type:"line", who:"qianye", exp:"sad", text:"我刚刚还能记得你今早穿的颜色——现在不记得了。" },
    { type:"countdown", text:"听好——10 秒内你必须做出第一步反应。", seconds:4,
      options:[
        { text:"打开她的接口仓盖。", success:true, flag:"crisis_step1", next:"q_ch9_step1_ok" },
        { text:"先扶住她。", success:false, flag:"hold_q", next:"q_ch9_step1_hold" },
        { text:"叫援助。", success:false, next:"q_ch9_step1_call" }
      ]
    },
    { type:"label", id:"q_ch9_step1_hold" },
    { type:"line", who:"qianye", exp:"sad", text:"……不是先扶我。先开仓盖。" },
    { type:"line", who:"qianye", exp:"sad", text:"——别让感性害了我。" },
    { type:"jump", to:"q_ch9_step1_ok" },
    { type:"label", id:"q_ch9_step1_call" },
    { type:"line", who:"qianye", exp:"sad", text:"……来不及了。修复师，你来。" },
    { type:"line", who:"qianye", exp:"sad", text:"我没有 30 秒等他们到。" },
    { type:"label", id:"q_ch9_step1_ok" },
    { type:"narr", scene:"archive", text:"仓盖打开。三个零件散落在你面前。" },
    { type:"narr", scene:"archive", text:"——主导线、中和器、调节阀。" },
    { type:"narr", scene:"archive", text:"她侧着脸，闭着眼。睫毛上挂着一颗未落下的水珠。" },
    { type:"drag",
      text:"把正确的零件拖入接口。一次机会。",
      hint:"她说过：「主」「中和」「甜」三段——这次不是咖啡，是神经导线",
      items:[ { label:"主导线" }, { label:"中和器" }, { label:"调节阀" } ],
      targets:[
        { id:"main", label:"主接口" },
        { id:"sub",  label:"调节" },
        { id:"sweet", label:"反馈" }
      ],
      answer:{ "0":"main", "1":"sub", "2":"sweet" },
      success:{ flag:"crisis_passed", aff:{qianye:5}, next:"q_ch9_pass" },
      fail:{ flag:"crisis_failed", aff:{qianye:-3}, next:"q_ch9_fail" }
    },
    { type:"label", id:"q_ch9_fail" },
    { type:"line", who:"qianye", exp:"sad", text:"……" },
    { type:"line", who:"qianye", exp:"sad", text:"修复师……你的手在抖。" },
    { type:"narr", scene:"archive", fx:"flash", text:"她的神经接口冒出蓝色火花。" },
    { type:"be", title:"BE3 · 错误的修复",
      en:"Wrong Repair",
      body:"你慌了。零件接错了一根。\n她的记忆被永久压缩。胶囊舱重新封闭。\n你站在档案库里很久——但她不会再为你醒来。\n\n12 年前那个测过 9.81 的女人，从此只剩下一个数字。" },
    { type:"label", id:"q_ch9_pass" },
    { type:"line", who:"qianye", exp:"blush", text:"……" },
    { type:"line", who:"qianye", exp:"blush", text:"修复师……" },
    { type:"line", who:"qianye", exp:"blush", text:"你的手——和我哥哥一样稳。" , important:true },
    { type:"line", who:"player", text:"（你看见自己的手指——指甲缘有一道极细的旧疤。）" },
    { type:"line", who:"player", text:"（——你不记得这道疤是怎么来的。）" },

    /* ---------- Ch10 真相 ---------- */
    { type:"chapter", day:3, name:"第十章 · 真相", en:"Ch.10 · The Truth", scene:"archive" },
    { type:"line", who:"qianye", exp:"calm", scene:"archive", text:"修复师……我现在告诉你 12 年前的全部。" },
    { type:"line", who:"qianye", exp:"calm", text:"我做的实验，叫「跨星际记忆传输」。" },
    { type:"line", who:"qianye", exp:"sad", text:"原理：我把我的记忆，传送到「未来与我相遇的人」脑中。" },
    { type:"line", who:"qianye", exp:"sad", text:"那时只有一个候选人——我哥哥林夕。" },
    { type:"line", who:"qianye", exp:"sad", text:"但他在事故里被植入了机械义体。" },
    { type:"line", who:"qianye", exp:"sad", text:"——大脑无法承担一个完整生命的记忆。" },
    { type:"line", who:"qianye", exp:"sad", text:"系统说他活下来了。但他自己说他死了。" },
    { type:"line", who:"qianye", exp:"sad", text:"于是他做了一个决定。" },
    { type:"line", who:"qianye", exp:"sad", text:"——他把自己的记忆，又传给了下一个人。" },
    { type:"line", who:"qianye", exp:"sad", text:"——也就是「修复师」这个身份。" , important:true },
    { type:"line", who:"player", text:"……" },
    { type:"line", who:"player", text:"（你的胸口像被人用一只温柔却坚定的手按住。）" },
    { type:"swipe",
      text:"慢慢握住她的手——她在颤抖。",
      direction:"right",
      dirHint:"向右滑 · 握住",
      reveal:"assets/cg/qianye_he.png",
      success:{ flag:"hand_q", aff:{qianye:3}, next:"q_ch10_after" },
      fail:{ next:"q_ch10_after" }
    },
    { type:"label", id:"q_ch10_after" },
    { type:"line", who:"qianye", exp:"sad", text:"——所以「修复师」不是一个人。" },
    { type:"line", who:"qianye", exp:"sad", text:"是一段链条。" },
    { type:"line", who:"qianye", exp:"sad", text:"我哥哥是第一段。你是第二段。" },
    { type:"line", who:"qianye", exp:"sad", text:"——也可能是最后一段。" },

    /* ---------- Ch11 第二次抉择（打字 · 写名字） ---------- */
    { type:"chapter", day:3, name:"第十一章 · 第二次抉择", en:"Ch.11 · The Second Choice", scene:"archive" },
    { type:"line", who:"qianye", exp:"sad", scene:"archive", text:"修复师……不。" },
    { type:"line", who:"qianye", exp:"sad", text:"我决定叫你的名字。" },
    { type:"line", who:"qianye", exp:"sad", text:"——你叫什么？" },
    { type:"line", who:"player", text:"（屏幕给你提示。但你的指尖知道答案。）" },
    { type:"typing",
      text:"亲手输入你的名字。",
      prompt:"如果你已经认识到你是谁——写下「林夕」。",
      answer:"林夕",
      tolerance:0,
      success:{ flag:"truth_qianye", aff:{qianye:5}, next:"q_ch11_pass" },
      fail:{ flag:"truth_failed", aff:{qianye:-1}, next:"q_ch11_fail" }
    },
    { type:"label", id:"q_ch11_pass" },
    { type:"line", who:"qianye", exp:"blush", text:"……终于。" },
    { type:"line", who:"qianye", exp:"blush", text:"林夕，你回来了。" , important:true },
    { type:"line", who:"qianye", exp:"calm", text:"——12 年。" },
    { type:"line", who:"qianye", exp:"calm", text:"我醒来过 196 次。" },
    { type:"line", who:"qianye", exp:"calm", text:"前 195 次都是别的修复师。" },
    { type:"line", who:"qianye", exp:"smile", text:"第 196 次，是你。" },
    { type:"jump", to:"q_ch11_close" },
    { type:"label", id:"q_ch11_fail" },
    { type:"line", who:"qianye", exp:"sad", text:"……" },
    { type:"line", who:"qianye", exp:"sad", text:"那我再等一会儿。" },
    { type:"line", who:"qianye", exp:"sad", text:"——醒来 196 次也没什么。" },
    { type:"line", who:"qianye", exp:"sad", text:"我可以再等 196 次。" },
    { type:"label", id:"q_ch11_close" },

    /* ---------- Ch12 高潮（QTE + CG） ---------- */
    { type:"chapter", day:3, name:"第十二章 · 高潮", en:"Ch.12 · The Climax", scene:"archive" },
    { type:"narr", scene:"archive", fx:"flash", text:"档案库的胶囊全部启动。光从胸口溢出来。" },
    { type:"narr", scene:"archive", fx:"flash", text:"她站起来。第一次完整地、不依赖胶囊地——「站立」在你面前。" },
    { type:"line", who:"qianye", exp:"smile", scene:"archive", text:"林夕。" },
    { type:"line", who:"qianye", exp:"smile", text:"陪我走完最后一段记忆走廊。" },
    { type:"line", who:"qianye", exp:"calm", text:"我们的呼吸要同步 8 次。" },
    { type:"line", who:"qianye", exp:"calm", text:"——8 是「无穷」躺下来的形状。" },
    { type:"qte",
      text:"她的心跳和你同步——别让节奏断。",
      beats:8,
      intervalMs:900,
      success:{ flag:"climax_passed", aff:{qianye:3}, next:"q_ch12_pass" },
      fail:{ flag:"climax_failed", aff:{qianye:-2}, next:"q_ch12_fail" }
    },
    { type:"label", id:"q_ch12_pass" },
    { type:"narr", scene:"archive", text:"你和她的呼吸同步了 8 次。所有记忆点亮。" },
    { type:"line", who:"qianye", exp:"blush", text:"……我看见你了。" },
    { type:"line", who:"qianye", exp:"blush", text:"我把所有记忆点亮的方式，全部交给你。" , important:true },
    { type:"jump", to:"q_ch12_close" },
    { type:"label", id:"q_ch12_fail" },
    { type:"narr", scene:"archive", text:"你的节奏断了一拍。她的记忆也断了一段。" },
    { type:"line", who:"qianye", exp:"sad", text:"……没事。" },
    { type:"line", who:"qianye", exp:"sad", text:"我可以接受 7 次。" },
    { type:"label", id:"q_ch12_close" },
    { type:"cg", id:"qianye_cg3", title:"同一个常数", scene:"archive", img:"qianye_he" },

    /* ---------- 隐藏 2：镜中林夕 ---------- */
    { type:"chapter", day:3, name:"隐藏 · 镜中林夕", en:"Hidden · Mirror", scene:"archive" },
    { type:"narr", scene:"archive", text:"档案库深处的镜面舱。" },
    { type:"narr", scene:"archive", text:"你看见自己——和她哥哥的脸重叠。" },
    { type:"player_silhouette", text:"（剪影站在镜里。）" },
    { type:"line", who:"narrator", text:"……终于。" },
    { type:"line", who:"narrator", text:"我们都在等你认出自己。" },
    { type:"line", who:"narrator", text:"——12 年。系统等你。她等你。我也等你。" },
    { type:"player_reveal" },
    { type:"line", who:"player", text:"（你笑了。也哭了。）" },
    { type:"line", who:"player", text:"（——林夕。原来你一直都在。）" },

    /* ---------- Ch13 后日谈 / 结局 ---------- */
    { type:"chapter", day:3, name:"第十三章 · 后日谈", en:"Ch.13 · Aftermath", scene:"deck" },
    { type:"narr", scene:"deck", text:"星舰穿过新的星云。她坐在你旁边。" },
    { type:"narr", scene:"deck", text:"舷窗外是一片以前从来没人命名过的蓝。" },
    { type:"line", who:"qianye", exp:"smile", scene:"deck", text:"林夕。" },
        { type:"line", who:"qianye", exp:"smile", text:"林夕。" },
    { type:"line", who:"qianye", exp:"smile", text:"下一次相遇，你要先认出我。" },
    { type:"line", who:"player", text:"……我已经认出了。" },
    { type:"line", who:"qianye", exp:"smile", text:"我知道。" },
    { type:"line", who:"qianye", exp:"smile", text:"——但我喜欢你再说一次。" },
    { type:"line", who:"player", text:"——我已经认出了你。" },
    { type:"line", who:"player", text:"——9.81。" },
    { type:"line", who:"player", text:"——2.46。" },
    { type:"line", who:"player", text:"——196。" },
    { type:"line", who:"player", text:"——这些都是你。" },
    { type:"line", who:"qianye", exp:"blush", text:"……" },
    { type:"line", who:"qianye", exp:"blush", text:"林夕，谢谢你。" },
    { type:"line", who:"qianye", exp:"smile", text:"——下一次相遇，换我先认出你。" , important:true },
    { type:"end", tag:"HE", title:"恒星轨道",
      en:"Stellar Orbit · True End",
      body:"你不再叫修复师。\n你陪她重新研究跨星际记忆。\n下一次相遇——你们已经先认出了彼此。\n\n而工作牌上的刻痕，永远不再闪光。" }
  ];
})();
