/* =====================================================================
 * 云璃线 v1 · 完整建设
 * 13 主线章 + 6 日常 + 2 隐藏 = 21 节点
 * 设定：玩家=修复师（M-195=林夕） / 云璃=被修复者（B-13）
 * 林夕暗线：你的工作牌缺失编号 M-195，对应云璃父亲（M-194）的学徒
 * ====================================================================== */
(function(){
  if (!window.STORY) window.STORY = {};

  window.STORY.yunli = [

    /* =========================================================
     *                       Day 1
     * ========================================================= */

    /* ---------- Ch1 工坊唤醒 ---------- */
    { type:"chapter", day:1, name:"第一章 · 工坊唤醒", en:"Ch.1 · Workshop", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"星舰「忘川号」B 舱 · 工坊区。", term:{ name:"工坊区", def:"星舰的机械维修舱段，被修复者云璃 12 年前的工作场所。" } },
    { type:"narr", scene:"corridor", text:"档案号 B-13：云璃 / 26 岁 / 机械工程师 / 12 年前因引擎事故自愿封存。" },
    { type:"narr", scene:"corridor", fx:"flash", text:"你戴上神经接口。眼前的胶囊舱缓缓打开。" },
    { type:"line", who:"yunli", exp:"calm", scene:"corridor", text:"……" },
    { type:"line", who:"yunli", exp:"calm", text:"……糟。我又醒了。" },
    { type:"line", who:"player", text:"（一个红发女孩从胶囊里翻出来，落地时一手扶住地面，像一只刚醒的猫。）" },
    { type:"line", who:"yunli", exp:"smile", text:"喂，新来的修复师？" },
    { type:"line", who:"yunli", exp:"smile", text:"……你看起来不太像修复师。" },
    { type:"line", who:"player", text:"……为什么？" },
    { type:"line", who:"yunli", exp:"smile", text:"修复师都板着脸。" },
    { type:"line", who:"yunli", exp:"smile", text:"你脸上写着：我不知道接下来要做什么。" },
    { type:"line", who:"player", text:"……" },
    { type:"line", who:"yunli", exp:"smile", text:"放心，我教你。" },
    { type:"line", who:"yunli", exp:"calm", text:"先帮我个忙——把那把三号扳手递给我。" },
    { type:"countdown", text:"她伸出手等你递扳手。三种工具混在一起，你认得哪一把？", seconds:5,
      options:[
        { text:"递三号扳手（中等开口）。", success:true, flag:"wrench_3", aff:{yunli:2}, next:"q_yl_ch1_wrench_ok" },
        { text:"递最重的那把。", success:false, aff:{yunli:0}, next:"q_yl_ch1_wrench_wrong" },
        { text:"……我分不清。", success:false, aff:{yunli:-1}, next:"q_yl_ch1_wrench_idk" }
      ]
    },
    { type:"label", id:"q_yl_ch1_wrench_ok" },
    { type:"line", who:"yunli", exp:"smile", text:"……" },
    { type:"line", who:"yunli", exp:"smile", text:"你手感不错。" },
    { type:"line", who:"yunli", exp:"calm", text:"上一任修复师连「三号」两个字都没听明白。" },
    { type:"jump", to:"q_yl_ch1_after_wrench" },
    { type:"label", id:"q_yl_ch1_wrench_wrong" },
    { type:"line", who:"yunli", exp:"calm", text:"……是三号。中等开口的。" },
    { type:"line", who:"yunli", exp:"smile", text:"没事，机械师也不是天生的。" },
    { type:"jump", to:"q_yl_ch1_after_wrench" },
    { type:"label", id:"q_yl_ch1_wrench_idk" },
    { type:"line", who:"yunli", exp:"smile", text:"行吧，我自己拿。" },
    { type:"line", who:"yunli", exp:"calm", text:"——但是，修复师，你要学。" },
    { type:"label", id:"q_yl_ch1_after_wrench" },
    { type:"line", who:"yunli", exp:"calm", text:"按理说我每次苏醒，就该被新修复师按部就班地评估、归档、重新封存。" },
    { type:"line", who:"yunli", exp:"smile", text:"但我不打算让你按部就班。" },
    { type:"line", who:"yunli", exp:"smile", text:"**修复我之前，先认识我。**", important:true },
    { type:"line", who:"player", text:"（她的扳手在你眼前晃了晃。）" },
    { type:"line", who:"yunli", exp:"smile", text:"——成交？" },

    /* ---------- Ch2 三件物 ---------- */
    { type:"chapter", day:1, name:"第二章 · 三件物", en:"Ch.2 · Three Things", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她带你回到工坊深处。台面上摆着三样东西。" },
    { type:"line", who:"yunli", exp:"calm", scene:"corridor", text:"我醒过来时，胶囊里塞着这三样。" },
    { type:"line", who:"yunli", exp:"calm", text:"一把扳手——是我的。" },
    { type:"line", who:"yunli", exp:"calm", text:"一颗机械齿轮——也是我的。" },
    { type:"line", who:"yunli", exp:"sad", text:"还有一张照片，照片里是一个戴眼镜的男人。" },
    { type:"line", who:"yunli", exp:"sad", text:"——这个人不是我。" },
    { type:"choice", options:[
      { text:"那是你父亲吗？", aff:{yunli:2}, flag:"guess_dad", next:"q_yl_ch2_dad" },
      { text:"也许是上一任修复师？", aff:{yunli:3}, flag:"guess_rep", next:"q_yl_ch2_rep" },
      { text:"……让我看看。", aff:{yunli:1}, next:"q_yl_ch2_look" }
    ]},
    { type:"label", id:"q_yl_ch2_dad" },
    { type:"line", who:"yunli", exp:"sad", text:"……" },
    { type:"line", who:"yunli", exp:"sad", text:"你怎么知道？" },
    { type:"line", who:"yunli", exp:"calm", text:"我父亲也是修复师。M 系列的，编号他从来不让我看。" },
    { type:"jump", to:"q_yl_ch2_close" },
    { type:"label", id:"q_yl_ch2_rep" },
    { type:"line", who:"yunli", exp:"calm", text:"……也有可能。" },
    { type:"line", who:"yunli", exp:"sad", text:"但你为什么觉得是？" },
    { type:"line", who:"player", text:"（你说不清。但那张照片里的人，让你胸口钝钝地动了一下。）" },
    { type:"jump", to:"q_yl_ch2_close" },
    { type:"label", id:"q_yl_ch2_look" },
    { type:"line", who:"yunli", exp:"calm", text:"嗯。看吧。" },
    { type:"label", id:"q_yl_ch2_close" },
    { type:"narr", scene:"corridor", text:"她把照片推到你面前。照片角落有一行被划掉的字。" },
    { type:"line", who:"player", text:"……这行字被划过。但似乎是个名字。" },
    { type:"line", who:"yunli", exp:"sad", text:"我也看不清。" },
    { type:"line", who:"yunli", exp:"sad", text:"**我只记得他抱我的时候，肩膀上有油的味道。**", important:true },

    /* ---------- Ch3 摸引擎（触摸） ---------- */
    { type:"chapter", day:1, name:"第三章 · 引擎", en:"Ch.3 · Engine", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她把你拉到工坊正中。一台老旧的引擎沉默地立在那里。" },
    { type:"line", who:"yunli", exp:"calm", scene:"corridor", text:"这是 12 年前我出事那天的引擎。", term:{ name:"引擎事故", def:"12 年前一次失败的试飞，云璃为救人受伤，自愿封存。详情档案残缺。" } },
    { type:"line", who:"yunli", exp:"calm", text:"系统把它和我一起封存，说是「心理锚点」。" },
    { type:"line", who:"yunli", exp:"smile", text:"……我每次苏醒，第一件事就是过来摸它。" },
    { type:"line", who:"yunli", exp:"calm", text:"你来——一起摸。" },
    { type:"touch",
      text:"她让你摸引擎不同的位置。每个位置都让她想起不同的事。",
      img:"assets/portraits/yunli.png",
      hint:"摸不同区域会得到不同回应",
      regions:[
        { x:30, y:35, r:9, label:"散热栅", flag:"touch_grid", aff:{yunli:1}, next:"q_yl_ch3_grid" },
        { x:50, y:55, r:10, label:"心轴", flag:"touch_core", aff:{yunli:3}, next:"q_yl_ch3_core" },
        { x:70, y:75, r:9, label:"接口插槽", flag:"touch_port", aff:{yunli:2}, next:"q_yl_ch3_port" }
      ]
    },
    { type:"label", id:"q_yl_ch3_grid" },
    { type:"line", who:"yunli", exp:"smile", text:"……散热栅。" },
    { type:"line", who:"yunli", exp:"smile", text:"我小时候喜欢把硬币塞进栅缝看它弹出来。" },
    { type:"jump", to:"q_yl_ch3_after_touch" },
    { type:"label", id:"q_yl_ch3_core" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"心轴。" },
    { type:"line", who:"yunli", exp:"sad", text:"出事那天，我抱着的就是这一根。" },
    { type:"line", who:"yunli", exp:"sad", text:"——我抱着它，把另一个人推出了引擎舱。" },
    { type:"jump", to:"q_yl_ch3_after_touch" },
    { type:"label", id:"q_yl_ch3_port" },
    { type:"line", who:"yunli", exp:"calm", text:"……接口插槽。" },
    { type:"line", who:"yunli", exp:"calm", text:"这个槽 12 年来一直是空的。" },
    { type:"line", who:"yunli", exp:"smile", text:"它在等一个对的人插进来。" },
    { type:"label", id:"q_yl_ch3_after_touch" },
    { type:"line", who:"yunli", exp:"calm", text:"修复师。" },
    { type:"line", who:"yunli", exp:"calm", text:"你的指头比上一任稳。" },
    { type:"line", who:"yunli", exp:"smile", text:"——你以前做过机械吗？" },
    { type:"choice", options:[
      { text:"……不记得了。", aff:{yunli:1}, next:"q_yl_ch3_close" },
      { text:"我手里好像有别人的肌肉记忆。", aff:{yunli:3}, flag:"honest_muscle", next:"q_yl_ch3_close" },
      { text:"也许有过。我不确定。", aff:{yunli:2}, next:"q_yl_ch3_close" }
    ]},
    { type:"label", id:"q_yl_ch3_close" },
    { type:"line", who:"yunli", exp:"calm", text:"嗯。" },
    { type:"line", who:"yunli", exp:"smile", text:"那就先把它借来用一阵。" },

    /* ---------- Ch4 第一次合作（拖拽） ---------- */
    { type:"chapter", day:1, name:"第四章 · 共修", en:"Ch.4 · Co-repair", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她说要让你做一件够格的修复师该做的事。" },
    { type:"line", who:"yunli", exp:"smile", scene:"corridor", text:"今晚 21:00，B 区有个小故障。我修，你打副手。" },
    { type:"line", who:"player", text:"……副手都做什么？" },
    { type:"line", who:"yunli", exp:"smile", text:"递东西，看着我，不要打断我。" },
    { type:"line", who:"yunli", exp:"calm", text:"——这三件事比看起来难。" },
    { type:"drag",
      text:"按云璃的指令，依次把零件放进正确的位置：导电片 / 缓冲胶圈 / 紧固螺栓。",
      hint:"导电片是主、胶圈缓冲、螺栓固定",
      items:[ { label:"导电片" }, { label:"缓冲胶圈" }, { label:"紧固螺栓" } ],
      targets:[
        { id:"main", label:"导电接口" },
        { id:"sub", label:"缓冲层" },
        { id:"sweet", label:"固定环" }
      ],
      answer:{ "0":"main", "1":"sub", "2":"sweet" },
      success:{ flag:"repair_ok", aff:{yunli:3}, next:"q_yl_ch4_pass" },
      fail:{ flag:"repair_off", aff:{yunli:0}, next:"q_yl_ch4_fail" }
    },
    { type:"label", id:"q_yl_ch4_pass" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"你居然没递错。" },
    { type:"line", who:"yunli", exp:"smile", text:"修复师，你的手很有礼貌。" },
    { type:"line", who:"yunli", exp:"calm", text:"——我喜欢这种手。" },
    { type:"jump", to:"q_yl_ch4_close" },
    { type:"label", id:"q_yl_ch4_fail" },
    { type:"line", who:"yunli", exp:"smile", text:"……行吧。" },
    { type:"line", who:"yunli", exp:"smile", text:"以后我就别让你打副手了，我让你递水。" },
    { type:"label", id:"q_yl_ch4_close" },
    { type:"narr", scene:"corridor", text:"故障修复。引擎重新亮起一盏淡橙色的灯。" },
    { type:"line", who:"yunli", exp:"smile", text:"成功！" },
    { type:"line", who:"yunli", exp:"smile", text:"修复师——你今晚的奖励：" },
    { type:"line", who:"yunli", exp:"smile", text:"和我一起吃宵夜。" },
    { type:"line", who:"yunli", exp:"calm", text:"**——你不许拒绝。**", important:true },
    { type:"cg", id:"yunli_cg1", title:"第一次合作", scene:"corridor", img:"yunli_d1" },
    { type:"mail", id:"sys_d1_yl", role:"system", title:"修复师 · 日报", body:"Day 1 完成。B-13 修复进度：6% → 11%。\n\n附：B-13 心率在与你合作时下降 18%，比单独工作更稳定。" },

    /* ---------- 日常 1：宵夜 ---------- */
    { type:"chapter", day:1, name:"日常 · 工坊宵夜", en:"Daily · Midnight Snack", scene:"cabin" },
    { type:"narr", scene:"cabin", text:"凌晨 23:40。她在工坊角落支起一张折叠小桌。" },
    { type:"line", who:"yunli", exp:"smile", scene:"cabin", text:"自热米饭加一根香肠。" },
    { type:"line", who:"yunli", exp:"smile", text:"——别嫌弃，星舰上能搞到的就这么多。" },
    { type:"choice", options:[
      { text:"我吃过更糟的。", aff:{yunli:1}, next:"q_yl_d1_eat_a" },
      { text:"你今天累了，我来加热。", aff:{yunli:3}, flag:"care_y", next:"q_yl_d1_eat_b" },
      { text:"……我不饿。", aff:{yunli:-1}, next:"q_yl_d1_eat_c" }
    ]},
    { type:"label", id:"q_yl_d1_eat_a" },
    { type:"line", who:"yunli", exp:"smile", text:"好家伙。" },
    { type:"jump", to:"q_yl_d1_close" },
    { type:"label", id:"q_yl_d1_eat_b" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"修复师，你这一句把我哽了一下。" },
    { type:"line", who:"yunli", exp:"smile", text:"很久没人对我说「你累了」。" },
    { type:"jump", to:"q_yl_d1_close" },
    { type:"label", id:"q_yl_d1_eat_c" },
    { type:"line", who:"yunli", exp:"calm", text:"……行吧。那我自己吃。" },
    { type:"line", who:"yunli", exp:"sad", text:"修复师，你不饿，至少坐一会儿。" },
    { type:"label", id:"q_yl_d1_close" },
    { type:"line", who:"yunli", exp:"smile", text:"修复师，你的胃和我的胃，今晚算是认识了。" },

    /* ---------- 日常 2：扳手箱 ---------- */
    { type:"chapter", day:1, name:"日常 · 扳手箱", en:"Daily · The Wrench Box", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她把一只老旧的扳手箱推到你面前。" },
    { type:"line", who:"yunli", exp:"calm", scene:"corridor", text:"修复师。这一箱扳手——是我父亲的。" },
    { type:"line", who:"yunli", exp:"calm", text:"他出事前，把箱子留给了我。" },
    { type:"line", who:"yunli", exp:"sad", text:"……可我打开箱子那天，最里面那把不见了。" },
    { type:"line", who:"player", text:"……不见了？" },
    { type:"line", who:"yunli", exp:"sad", text:"嗯。第一格永远是空的。" },
    { type:"line", who:"yunli", exp:"calm", text:"你来翻一翻——看看你能在第一格放什么。" },
    { type:"choice", options:[
      { text:"放上我自己手里这一把（如果有）。", aff:{yunli:3}, flag:"give_wrench", next:"q_yl_d2_give" },
      { text:"留着空——也许是给某个人留的。", aff:{yunli:2}, flag:"respect_box", next:"q_yl_d2_keep" },
      { text:"我没有可以放的。", aff:{yunli:0}, next:"q_yl_d2_close" }
    ]},
    { type:"label", id:"q_yl_d2_give" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"修复师，你这是认了我的箱子。" },
    { type:"line", who:"yunli", exp:"smile", text:"——我下次让你也认了我。" },
    { type:"jump", to:"q_yl_d2_close" },
    { type:"label", id:"q_yl_d2_keep" },
    { type:"line", who:"yunli", exp:"sad", text:"……" },
    { type:"line", who:"yunli", exp:"sad", text:"是的。这一格——是给我父亲留的。" },
    { type:"line", who:"yunli", exp:"sad", text:"等他回来，他自己放进去。" },
    { type:"label", id:"q_yl_d2_close" },

    /* =========================================================
     *                       Day 2
     * ========================================================= */

    /* ---------- Ch5 失重之吻（QTE） ---------- */
    { type:"chapter", day:2, name:"第五章 · 舱外维修", en:"Ch.5 · EVA", scene:"deck" },
    { type:"narr", scene:"deck", text:"清晨 5:30。星舰外壳上有一处微小的裂痕，必须有人出舱去补。" },
    { type:"line", who:"yunli", exp:"calm", scene:"deck", text:"修复师。我出去。你看仪表。" },
    { type:"line", who:"player", text:"……我跟你出去。" },
    { type:"line", who:"yunli", exp:"sad", text:"你又不会失重。" },
    { type:"line", who:"player", text:"我学。" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"——你这么说，我就带你出去。" },
    { type:"narr", scene:"deck", text:"两人系紧安全绳，缓缓飘出气闸。星海在你们脚下铺开。" },
    { type:"line", who:"yunli", exp:"calm", text:"——别低头看，会眩晕。" },
    { type:"line", who:"yunli", exp:"calm", text:"跟着我的节奏，左手拉绳，右手扶我。" },
    { type:"qte",
      text:"跟上云璃的舱外移动节奏。8 拍内不要断。",
      beats:8,
      intervalMs:850,
      success:{ flag:"eva_pass", aff:{yunli:4}, next:"q_yl_ch5_pass" },
      fail:{ flag:"eva_fail", aff:{yunli:-2}, next:"q_yl_ch5_fail" }
    },
    { type:"label", id:"q_yl_ch5_pass" },
    { type:"narr", scene:"deck", text:"你们到达裂痕处。云璃用焊枪修补，你扶住她的腰。" },
    { type:"line", who:"yunli", exp:"smile", text:"……修复师。" },
    { type:"line", who:"yunli", exp:"blush", text:"你的手在抖。" },
    { type:"line", who:"player", text:"……（其实是你的心跳在抖。）" },
    { type:"line", who:"yunli", exp:"smile", text:"**——失重让吻变得很轻。**", important:true },
    { type:"line", who:"yunli", exp:"blush", text:"我说错了，不是吻，是——" },
    { type:"line", who:"yunli", exp:"blush", text:"……就是想说说话。" },
    { type:"cg", id:"yunli_cg2", title:"失重的距离", scene:"deck", img:"yunli_d2" },
    { type:"jump", to:"q_yl_ch5_close" },
    { type:"label", id:"q_yl_ch5_fail" },
    { type:"narr", scene:"deck", text:"你的动作慢了半拍，安全绳猛地绷直。" },
    { type:"line", who:"yunli", exp:"sad", text:"……新人。" },
    { type:"line", who:"yunli", exp:"sad", text:"下次别跟我出来。" },
    { type:"label", id:"q_yl_ch5_close" },

    /* ---------- Ch6 引擎告白（voice） ---------- */
    { type:"chapter", day:2, name:"第六章 · 引擎告白", en:"Ch.6 · Engine Vow", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"回到工坊。云璃靠着引擎坐下，让你坐在她旁边。" },
    { type:"line", who:"yunli", exp:"calm", scene:"corridor", text:"修复师。我问你一件事，要你说出来。" },
    { type:"line", who:"yunli", exp:"calm", text:"——你愿不愿意，做我的副手？" },
    { type:"line", who:"yunli", exp:"sad", text:"我不是说今晚的副手。" },
    { type:"line", who:"yunli", exp:"sad", text:"是以后所有引擎、所有修理、所有出舱——的副手。" },
    { type:"voice",
      text:"她在等你回答。说出来。",
      options:[
        { label:"我愿意做你的副手。", correct:true, aff:{yunli:5}, flag:"vow_yl_yes", next:"q_yl_ch6_yes" },
        { label:"……我考虑一下。", correct:false, aff:{yunli:0}, next:"q_yl_ch6_maybe" },
        { label:"修复师不该承诺这种事。", correct:false, aff:{yunli:-3}, flag:"vow_yl_no", next:"q_yl_ch6_no" }
      ]
    },
    { type:"label", id:"q_yl_ch6_yes" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"修复师，我录音了。" },
    { type:"line", who:"yunli", exp:"smile", text:"——你这句话，以后赖不掉。" },
    { type:"jump", to:"q_yl_ch6_close" },
    { type:"label", id:"q_yl_ch6_maybe" },
    { type:"line", who:"yunli", exp:"calm", text:"嗯。" },
    { type:"line", who:"yunli", exp:"sad", text:"——你慢慢考虑。" },
    { type:"line", who:"yunli", exp:"sad", text:"我等。" },
    { type:"jump", to:"q_yl_ch6_close" },
    { type:"label", id:"q_yl_ch6_no" },
    { type:"line", who:"yunli", exp:"sad", text:"……" },
    { type:"line", who:"yunli", exp:"sad", text:"好。修复师，你说得对。" },
    { type:"line", who:"yunli", exp:"sad", text:"那我也不强求。" },
    { type:"be", title:"BE1 · 错失的承诺",
      en:"Missed Vow",
      body:"她回到工坊。\n你再来时，她已经不愿意叫你的名字。\n\n第三天清晨，B-13 提前提交了封存申请。\n——你从此只在记录里见到她。" },
    { type:"label", id:"q_yl_ch6_close" },

    /* ---------- Ch7 父亲的工具（滑动） ---------- */
    { type:"chapter", day:2, name:"第七章 · 父亲的扳手", en:"Ch.7 · Father's Wrench", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她把那只缺一格的扳手箱再次摆在你面前。" },
    { type:"line", who:"yunli", exp:"calm", scene:"corridor", text:"修复师。" },
    { type:"line", who:"yunli", exp:"calm", text:"我父亲的最后一把扳手——我藏在引擎里。" },
    { type:"line", who:"yunli", exp:"sad", text:"今天，你帮我拿出来。" },
    { type:"swipe",
      text:"慢慢把引擎舱盖向右滑开。",
      direction:"right",
      dirHint:"向右滑",
      reveal:"assets/cg/yunli_he.png",
      success:{ flag:"father_wrench", aff:{yunli:3}, next:"q_yl_ch7_pass" },
      fail:{ next:"q_yl_ch7_fail" }
    },
    { type:"label", id:"q_yl_ch7_pass" },
    { type:"narr", scene:"corridor", text:"舱盖打开。里面是一把锈得几乎看不出形状的旧扳手。" },
    { type:"line", who:"yunli", exp:"sad", text:"……父亲的最后一把。" },
    { type:"line", who:"yunli", exp:"sad", text:"上面有刻字。" },
    { type:"line", who:"player", text:"（你拿到手里，看见两个字——林、夕。）" },
    { type:"anomaly", text:"⚠ 玩家身份耦合度 +25% · clue_lin_wrench 解锁", clue:"clue_lin_wrench" },
    { type:"line", who:"yunli", exp:"sad", text:"……修复师，你看到字了吗？" },
    { type:"choice", options:[
      { text:"……上面写着林夕。", aff:{yunli:3}, flag:"reveal_linxi", next:"q_yl_ch7_close" },
      { text:"我看不清。", aff:{yunli:0}, next:"q_yl_ch7_close" },
      { text:"——我可以不告诉你吗？", aff:{yunli:1}, flag:"hide_linxi", next:"q_yl_ch7_close" }
    ]},
    { type:"label", id:"q_yl_ch7_close" },
    { type:"jump", to:"q_yl_ch7_done" },
    { type:"label", id:"q_yl_ch7_fail" },
    { type:"line", who:"yunli", exp:"sad", text:"……盖卡住了。" },
    { type:"line", who:"yunli", exp:"sad", text:"下次我们再来。" },
    { type:"label", id:"q_yl_ch7_done" },

    /* ---------- Ch8 重大冲突（倒计时 BE） ---------- */
    { type:"chapter", day:2, name:"第八章 · 你是谁", en:"Ch.8 · Who Are You", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她突然挡在工坊门口。" },
    { type:"line", who:"yunli", exp:"sad", scene:"corridor", text:"修复师。" },
    { type:"line", who:"yunli", exp:"sad", text:"……我父亲那把扳手上的两个字，到底是什么？" },
    { type:"line", who:"yunli", exp:"sad", text:"我等了 12 年，问每一任修复师。" },
    { type:"line", who:"yunli", exp:"sad", text:"没人愿意告诉我。" },
    { type:"line", who:"yunli", exp:"sad", text:"——你呢？" },
    { type:"countdown", text:"她在等你的回答。", seconds:5,
      options:[
        { text:"是「林夕」。", success:true, flag:"truth_linxi_now", aff:{yunli:5}, next:"q_yl_ch8_truth" },
        { text:"我看不清。", success:false, aff:{yunli:-1}, next:"q_yl_ch8_lie" },
        { text:"……让我先回去查一下。", success:false, aff:{yunli:0}, next:"q_yl_ch8_dodge" },
        { text:"（沉默）", timeout:true, success:false, aff:{yunli:-3}, flag:"silence_yl", next:"q_yl_ch8_silence" }
      ]
    },
    { type:"label", id:"q_yl_ch8_truth" },
    { type:"line", who:"yunli", exp:"sad", text:"……林夕。" },
    { type:"line", who:"yunli", exp:"sad", text:"林。夕。" },
    { type:"line", who:"yunli", exp:"sad", text:"——这是我父亲学徒的名字。" },
    { type:"line", who:"yunli", exp:"sad", text:"那年事故——我推出引擎舱的人，就是这个学徒。" },
    { type:"line", who:"yunli", exp:"sad", text:"**他活下来了，但他从此不愿意见我。**", important:true },
    { type:"jump", to:"q_yl_ch8_close" },
    { type:"label", id:"q_yl_ch8_lie" },
    { type:"line", who:"yunli", exp:"sad", text:"……" },
    { type:"line", who:"yunli", exp:"sad", text:"好。那我等下一任修复师。" },
    { type:"jump", to:"q_yl_ch8_close" },
    { type:"label", id:"q_yl_ch8_dodge" },
    { type:"line", who:"yunli", exp:"sad", text:"……行。你回去查。" },
    { type:"line", who:"yunli", exp:"calm", text:"修复师，记得回来。" },
    { type:"jump", to:"q_yl_ch8_close" },
    { type:"label", id:"q_yl_ch8_silence" },
    { type:"line", who:"yunli", exp:"sad", text:"……" },
    { type:"line", who:"yunli", exp:"sad", text:"——好。" },
    { type:"line", who:"yunli", exp:"sad", text:"沉默是答案。" },
    { type:"be", title:"BE2 · 沉默的扳手",
      en:"Silent Wrench",
      body:"她不再问你。\n第二天清晨，工坊的灯关了。\n你站在引擎旁，那把锈扳手仍然在你手里——\n但你没有勇气把它放进她的箱子。" },
    { type:"label", id:"q_yl_ch8_close" },

    /* ---------- 日常 3：送扳手挂坠 ---------- */
    { type:"chapter", day:2, name:"日常 · 扳手挂坠", en:"Daily · Tiny Wrench", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她递给你一个银色的小挂坠，造型是一把迷你扳手。" },
    { type:"line", who:"yunli", exp:"calm", scene:"corridor", text:"……机械师的护身符。" },
    { type:"line", who:"yunli", exp:"smile", text:"我父亲送过我一个，我把那个埋了。" },
    { type:"line", who:"yunli", exp:"smile", text:"这个——我打了一个新的。给你。" },
    { type:"choice", options:[
      { text:"我会一直挂着。", aff:{yunli:3}, gift:"wrench", next:"q_yl_d3_take" },
      { text:"我不配。", aff:{yunli:0}, next:"q_yl_d3_decline" },
      { text:"——那我也送你点什么。", aff:{yunli:2}, flag:"return_gift", next:"q_yl_d3_return" }
    ]},
    { type:"label", id:"q_yl_d3_take" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"修复师，「一直」这个词你别乱用。" },
    { type:"line", who:"yunli", exp:"smile", text:"——但是听起来很爽。" },
    { type:"jump", to:"q_yl_d3_close" },
    { type:"label", id:"q_yl_d3_decline" },
    { type:"line", who:"yunli", exp:"sad", text:"……" },
    { type:"line", who:"yunli", exp:"calm", text:"行。我替你保管。" },
    { type:"jump", to:"q_yl_d3_close" },
    { type:"label", id:"q_yl_d3_return" },
    { type:"line", who:"yunli", exp:"smile", text:"……？" },
    { type:"line", who:"yunli", exp:"smile", text:"你打算送什么。" },
    { type:"line", who:"player", text:"（你不知道。但你想让她笑。）" },
    { type:"label", id:"q_yl_d3_close" },

    /* ---------- 日常 4：节拍合奏 ---------- */
    { type:"chapter", day:2, name:"日常 · 节拍合奏", en:"Daily · Beat Together", scene:"corridor" },
    { type:"narr", scene:"corridor", text:"她说想和你一起做一件无聊的事。" },
    { type:"line", who:"yunli", exp:"smile", scene:"corridor", text:"——敲扳手。" },
    { type:"line", who:"yunli", exp:"smile", text:"你跟我的节奏。" },
    { type:"choice", options:[
      { text:"来。", aff:{yunli:1}, mini:"yl", next:"q_yl_d4_close" },
      { text:"我节奏感不太行。", aff:{yunli:2}, flag:"shy_beat", next:"q_yl_d4_close" }
    ]},
    { type:"label", id:"q_yl_d4_close" },
    { type:"line", who:"yunli", exp:"smile", text:"……" },
    { type:"line", who:"yunli", exp:"smile", text:"修复师，你节奏比上一任稳得多。" },

    /* ---------- 隐藏 1：父亲档案 ---------- */
    { type:"chapter", day:2, name:"隐藏 · 父亲档案", en:"Hidden · Father's File", scene:"archive" },
    { type:"narr", scene:"archive", text:"档案库深处。她调出 M 系列编号档案。" },
    { type:"line", who:"yunli", exp:"sad", scene:"archive", text:"我父亲——M-194。" },
    { type:"line", who:"yunli", exp:"sad", text:"在他之前一任，M-193，是个老头。" },
    { type:"line", who:"yunli", exp:"sad", text:"在他之后一任——本来该是 M-195。" },
    { type:"line", who:"yunli", exp:"sad", text:"可是 M-195 的位置是空的。" },
    { type:"line", who:"yunli", exp:"sad", text:"被人为划掉。" },
    { type:"line", who:"player", text:"……被谁？" },
    { type:"line", who:"yunli", exp:"sad", text:"档案没说。" },
    { type:"line", who:"yunli", exp:"sad", text:"**——但 M-195 的入职日期，就是 12 年前我出事那天。**", important:true },
    { type:"line", who:"player", text:"（你的呼吸变浅。M 系列编号，正是你工作牌缺失的那一段。）" },
    { type:"anomaly", text:"⚠ 隐藏剧情解锁 · M-195 = 林夕（玩家本人？）", clue:"clue_m195" },

    /* =========================================================
     *                       Day 3
     * ========================================================= */

    /* ---------- Ch9 引擎危机（倒计时+拖拽 BE） ---------- */
    { type:"chapter", day:3, name:"第九章 · 引擎危机", en:"Ch.9 · Engine Crisis", scene:"corridor" },
    { type:"narr", scene:"corridor", fx:"flash", text:"凌晨警报：B-13 胶囊舱与主引擎共振，10 秒内需切断耦合。" },
    { type:"line", who:"yunli", exp:"sad", scene:"corridor", text:"……修复师，是 12 年前那次事故的重演。" },
    { type:"countdown", text:"10 秒。第一步反应。", seconds:4,
      options:[
        { text:"先关闭主引擎电源。", success:true, flag:"crisis_yl_step1", next:"q_yl_ch9_step_ok" },
        { text:"先扶住云璃。", success:false, aff:{yunli:1}, next:"q_yl_ch9_step_hold" },
        { text:"叫援助。", success:false, next:"q_yl_ch9_step_call" }
      ]
    },
    { type:"label", id:"q_yl_ch9_step_hold" },
    { type:"line", who:"yunli", exp:"sad", text:"——不是抱我。先关电源。" },
    { type:"jump", to:"q_yl_ch9_step_ok" },
    { type:"label", id:"q_yl_ch9_step_call" },
    { type:"line", who:"yunli", exp:"sad", text:"——来不及。你来。" },
    { type:"label", id:"q_yl_ch9_step_ok" },
    { type:"narr", scene:"corridor", text:"电源切断。三根导线散落在你面前。" },
    { type:"drag",
      text:"把正确的导线插回接口。一次机会。",
      hint:"主电源 / 缓冲层 / 反馈环——记得她说过的顺序",
      items:[ { label:"主电源" }, { label:"缓冲电容" }, { label:"反馈环" } ],
      targets:[
        { id:"main", label:"主接口" },
        { id:"sub", label:"缓冲" },
        { id:"sweet", label:"反馈" }
      ],
      answer:{ "0":"main", "1":"sub", "2":"sweet" },
      success:{ flag:"crisis_yl_pass", aff:{yunli:5}, next:"q_yl_ch9_pass" },
      fail:{ flag:"crisis_yl_fail", aff:{yunli:-3}, next:"q_yl_ch9_fail" }
    },
    { type:"label", id:"q_yl_ch9_fail" },
    { type:"line", who:"yunli", exp:"sad", text:"……" },
    { type:"narr", scene:"corridor", fx:"flash", text:"火花四溅。她的胶囊封闭。" },
    { type:"be", title:"BE3 · 12 年的重演",
      en:"Same Mistake",
      body:"导线错了一根。\n云璃的胶囊重新封死，警告音响成一片。\n12 年前的事故，在你手里重演了一次。\n\n——她没有醒来。" },
    { type:"label", id:"q_yl_ch9_pass" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"修复师，你的手——和我父亲一样稳。" },
    { type:"line", who:"player", text:"（你的指节微微颤抖。但你没有出错。）" },

    /* ---------- Ch10 真相 ---------- */
    { type:"chapter", day:3, name:"第十章 · 真相", en:"Ch.10 · The Truth", scene:"archive" },
    { type:"line", who:"yunli", exp:"calm", scene:"archive", text:"修复师。" },
    { type:"line", who:"yunli", exp:"calm", text:"我现在告诉你 12 年前的全部。" },
    { type:"line", who:"yunli", exp:"sad", text:"我父亲是 M-194。" },
    { type:"line", who:"yunli", exp:"sad", text:"他在我 14 岁那年，把一个学徒带回家。" },
    { type:"line", who:"yunli", exp:"sad", text:"——学徒叫林夕，沉默、专注、手指稳。" },
    { type:"line", who:"yunli", exp:"sad", text:"他被父亲选为 M-195 接班人。" },
    { type:"line", who:"yunli", exp:"sad", text:"事故发生时，林夕和我父亲都在引擎舱里。" },
    { type:"line", who:"yunli", exp:"sad", text:"父亲推我出去。我拉住林夕。" },
    { type:"line", who:"yunli", exp:"sad", text:"林夕活下来了，但他被植入义体。" },
    { type:"line", who:"yunli", exp:"sad", text:"父亲——没出来。", term:{ name:"M-195", def:"被划掉的修复师编号，对应 12 年前事故中被植入义体的学徒林夕。" } },
    { type:"line", who:"yunli", exp:"sad", text:"林夕从此把自己除名。" },
    { type:"line", who:"yunli", exp:"sad", text:"——M-195 是空号。" },
    { type:"line", who:"yunli", exp:"sad", text:"他后来去了哪里——没人知道。" },
    { type:"swipe",
      text:"她伸出手。慢慢握住。",
      direction:"left",
      dirHint:"向左滑 · 握住",
      reveal:"assets/cg/yunli_he.png",
      success:{ flag:"hand_yl", aff:{yunli:3}, next:"q_yl_ch10_after" },
      fail:{ next:"q_yl_ch10_after" }
    },
    { type:"label", id:"q_yl_ch10_after" },

    /* ---------- Ch11 第二次抉择（voice 说编号） ---------- */
    { type:"chapter", day:3, name:"第十一章 · 第二次抉择", en:"Ch.11 · The Second Choice", scene:"archive" },
    { type:"line", who:"yunli", exp:"sad", scene:"archive", text:"修复师。" },
    { type:"line", who:"yunli", exp:"sad", text:"——你工作牌中段四位编号，是什么？" },
    { type:"line", who:"player", text:"（你看自己的工作牌。空白。但你的喉咙里有答案。）" },
    { type:"voice",
      text:"她在等你说出你的编号。",
      options:[
        { label:"M-195。", correct:true, aff:{yunli:5}, flag:"truth_yl_m195", next:"q_yl_ch11_pass" },
        { label:"我没有编号。", correct:false, aff:{yunli:0}, next:"q_yl_ch11_fail" },
        { label:"——我不能说。", correct:false, aff:{yunli:-1}, next:"q_yl_ch11_fail" }
      ]
    },
    { type:"label", id:"q_yl_ch11_pass" },
    { type:"line", who:"yunli", exp:"blush", text:"……" },
    { type:"line", who:"yunli", exp:"blush", text:"**林夕。**", important:true },
    { type:"line", who:"yunli", exp:"sad", text:"你回来了。" },
    { type:"line", who:"yunli", exp:"calm", text:"我父亲——他生前最后一句话是托我转告你。" },
    { type:"line", who:"yunli", exp:"calm", text:"——他说：对不起，这把扳手没给你。" },
    { type:"jump", to:"q_yl_ch11_close" },
    { type:"label", id:"q_yl_ch11_fail" },
    { type:"line", who:"yunli", exp:"sad", text:"……" },
    { type:"line", who:"yunli", exp:"sad", text:"——好。" },
    { type:"line", who:"yunli", exp:"sad", text:"那我再等一任。" },
    { type:"label", id:"q_yl_ch11_close" },

    /* ---------- Ch12 高潮（QTE + CG） ---------- */
    { type:"chapter", day:3, name:"第十二章 · 高潮", en:"Ch.12 · The Climax", scene:"corridor" },
    { type:"narr", scene:"corridor", fx:"flash", text:"工坊所有灯重新亮起。引擎中央那个 12 年来空着的接口槽——" },
    { type:"line", who:"yunli", exp:"smile", scene:"corridor", text:"——林夕。" },
    { type:"line", who:"yunli", exp:"smile", text:"把这把扳手插进去。" },
    { type:"line", who:"yunli", exp:"calm", text:"是空了 12 年的位置。今天该被填上了。" },
    { type:"qte",
      text:"和云璃同步拧动扳手 7 圈。",
      beats:7,
      intervalMs:900,
      success:{ flag:"climax_yl_pass", aff:{yunli:3}, next:"q_yl_ch12_pass" },
      fail:{ flag:"climax_yl_fail", aff:{yunli:-2}, next:"q_yl_ch12_fail" }
    },
    { type:"label", id:"q_yl_ch12_pass" },
    { type:"narr", scene:"corridor", text:"扳手卡住的瞬间，引擎深处亮起一束温暖的橙光。" },
    { type:"line", who:"yunli", exp:"blush", text:"……我父亲——看见了。" },
    { type:"jump", to:"q_yl_ch12_close" },
    { type:"label", id:"q_yl_ch12_fail" },
    { type:"narr", scene:"corridor", text:"你的手抖了一下。扳手卡偏了。" },
    { type:"line", who:"yunli", exp:"sad", text:"……差一点。" },
    { type:"label", id:"q_yl_ch12_close" },
    { type:"cg", id:"yunli_cg3", title:"父亲的位置", scene:"corridor", img:"yunli_he" },

    /* ---------- 隐藏 2：旧影像 ---------- */
    { type:"chapter", day:3, name:"隐藏 · 父亲的影像", en:"Hidden · Father Footage", scene:"archive" },
    { type:"narr", scene:"archive", text:"档案库角落，一段被设为「私人」的影像自动播放。" },
    { type:"line", who:"narrator", text:"——林夕，等你长大，把这把扳手交还给我女儿。" },
    { type:"line", who:"narrator", text:"——告诉她，爸爸没什么遗憾。" },
    { type:"line", who:"narrator", text:"……只有一件——没看见她笑过我那种笑。" },
    { type:"player_silhouette", text:"（你的剪影站在屏幕前。）" },
    { type:"player_reveal" },
    { type:"line", who:"player", text:"……" },
    { type:"line", who:"player", text:"——叔叔。我做到了。" },

    /* ---------- Ch13 后日谈 ---------- */
    { type:"chapter", day:3, name:"第十三章 · 后日谈", en:"Ch.13 · Aftermath", scene:"deck" },
    { type:"narr", scene:"deck", text:"星舰穿过一片橙色的星云。云璃坐在你旁边，扳手挂坠在她锁骨下闪光。" },
    { type:"line", who:"yunli", exp:"smile", scene:"deck", text:"林夕。" },
    { type:"line", who:"yunli", exp:"smile", text:"——以后你每出舱一次，我跟一次。" },
    { type:"line", who:"player", text:"……不公平。我每次都被你带飞。" },
    { type:"line", who:"yunli", exp:"smile", text:"那你也带我飞一次。" },
    { type:"line", who:"yunli", exp:"smile", text:"**——下一次相遇，换我递扳手。**", important:true },
    { type:"end", tag:"HE", title:"引擎余温",
      en:"Engine Afterglow · True End",
      body:"你不再叫修复师。\n你成了她正式的副手。\n父亲留下的那把扳手，永远在引擎中央。\n\n下一次相遇——你们已经先认出了彼此。" }
  ];
})();
